<template>
  <div class="v2-page profile-page">
    <van-button v-if="failed" block @click="loadData">{{ t('audit.loadFailed') }}</van-button>
    <header class="profile-top"><button class="profile-notifications" :aria-label="t('profile.notifications')" @click="router.push('/profile/notifications')"><van-icon name="bell"/><span v-if="notificationStore.unreadCount">{{ notificationStore.unreadCount > 99 ? '99+' : notificationStore.unreadCount }}</span></button></header>
    <section class="identity" role="button" tabindex="0" @click="router.push('/profile/account')" @keydown.enter="router.push('/profile/account')"><img :src="avatarUrl" :alt="displayName" @error="onAvatarError"><div><h2>{{ displayName }} <span v-if="isVip"><van-icon name="gem-o"/>{{ t('v2.profile.vip') }}</span></h2><p>{{ maskedEmail }}</p></div></section>
    <section class="stats v2-card"><button @click="router.push('/profile/credits')"><span>{{ t('v2.profile.points') }}</span><strong>{{ formatNumber(billing.credits) }}</strong></button><button @click="router.push({path:'/market/my-purchases',query:{asset_type:'script_template'}})"><span>{{ t('v2.profile.boughtStrategies') }}</span><strong>{{ purchaseCount }}</strong></button><button @click="router.push({path:'/market/my-purchases',query:{asset_type:'indicator'}})"><span>{{ t('v2.profile.boughtIndicators') }}</span><strong>{{ indicatorCount }}</strong></button></section>
    <button class="account v2-card" @click="router.push('/profile/credentials')"><ExchangeLogo :exchange="primaryCredential?.exchange_id || ''" :size="48" /><span><strong>{{ t('v2.profile.broker') }}</strong><b>{{ primaryCredential?.name || t('audit.noAccount') }}</b><small>{{ primaryCredential?.exchange_id || t('v2.profile.notConnected') }}</small></span><van-icon name="arrow"/></button>

    <section v-for="group in menuGroups" :key="group.title" class="menu-block"><h2>{{ group.title }}</h2><div class="menu-list v2-card"><button v-for="item in group.items" :key="item.path||item.key" @click="handleMenu(item)"><van-icon :name="item.icon"/><span>{{ item.label }}</span><em v-if="item.meta">{{ item.meta }}</em><van-icon name="arrow"/></button></div></section>
    <van-button class="logout-button" block plain @click="logout">{{ t('profile.logout') }}</van-button>
  </div>
</template>

<script setup>
import { computed,onActivated,reactive,ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute,useRouter } from 'vue-router'
import { authApi,credentialsApi,getBaseUrl,marketApi,strategyApi,userApi } from '@/api'
import { SUPPORTED_LOCALES } from '@/locales'
import { useNotificationStore,useSettingsStore,useUserStore } from '@/stores'
import { showConfirmDialog } from 'vant'
import ExchangeLogo from '@/components/ExchangeLogo.vue'
import { getAssetType } from '@/utils/marketRoutes'
import logoUrl from '@/assets/slogo.png'
defineOptions({name:'ProfileV2'})
const {t}=useI18n(); const router=useRouter(); const route=useRoute(); const userStore=useUserStore(); const settingsStore=useSettingsStore(); const notificationStore=useNotificationStore(); const billing=reactive({credits:0,is_vip:false,vip_expires_at:null}); const credentials=ref([]); const primaryCredential=computed(()=>credentials.value[0]); const mfa=ref(null);const failed=ref(false); const credentialCount=ref(0); const purchaseCount=ref(0); const indicatorCount=ref(0);
const userInfo=computed(()=>userStore.userInfo); const displayName=computed(()=>userInfo.value?.nickname||userInfo.value?.username||t('v2.profile.title')); const maskedEmail=computed(()=>userInfo.value?.email||t('profile.account_subtitle')); const isVip=computed(()=>billing.is_vip||(billing.vip_expires_at&&new Date(billing.vip_expires_at).getTime()>Date.now())); const languageLabel=computed(()=>SUPPORTED_LOCALES.find(x=>x.value===settingsStore.locale)?.label||settingsStore.locale)
const avatarUrl=computed(()=>{const raw=String(userInfo.value?.avatar||'').trim();if(!raw)return logoUrl;if(/^(https?:|data:|blob:)/i.test(raw))return raw;const base=getBaseUrl().replace(/\/$/,'');return raw.startsWith('/')?`${base}${raw}`:`${base}/${raw}`})
const menuGroups=computed(()=>[
  {title:t('v2.profile.assetsServices'),items:[{label:t('v2.profile.myPurchases'),icon:'cart-o',path:'/market/my-purchases'},{label:t('v2.profile.pointsMember'),icon:'gem-o',path:'/profile/credits'},{label:t('profile.credits_recharge'),icon:'balance-pay',path:'/profile/credits'}]},
  {title:t('v2.profile.security'),items:[{label:t('v2.profile.accountSecurity'),icon:'shield-o',path:'/profile/security'},{label:t('v2.profile.mfa'),icon:'lock',path:'/profile/mfa',meta:mfa.value===null?'—':t(mfa.value?'profile.enabled':'profile.disabled')},{label:t('v2.profile.loginLog'),icon:'records-o',path:'/profile/login-logs'}]},
  {title:t('v2.profile.preferenceSupport'),items:[{label:t('v2.profile.notification'),icon:'bell',path:'/profile/notification-settings'},{label:t('v2.profile.languageTheme'),icon:'setting-o',path:'/profile/language',meta:languageLabel.value},{label:t('profile.referral'),icon:'friends-o',path:'/profile/referral'},{label:t('v2.profile.about'),icon:'info-o',path:'/profile/about'}]}
])
onActivated(loadData)
async function loadData(){failed.value=false;const r=await Promise.allSettled([userApi.getProfile(),credentialsApi.list(),loadPurchases(),strategyApi.getUnreadNotificationCount(),userApi.getMfaStatus()]);failed.value=r.some(x=>x.status==='rejected');if(r[0].status==='fulfilled'){const p=r[0].value.data;userStore.setUserInfo(p);Object.assign(billing,p?.billing||{})}if(r[1].status==='fulfilled'){credentials.value=r[1].value.data||[];credentialCount.value=credentials.value.length};if(r[2].status==='fulfilled'){const data=r[2].value.data;purchaseCount.value=(data?.items||[]).filter(x=>getAssetType(x)==='script_template').length;indicatorCount.value=(data?.items||[]).filter(x=>getAssetType(x)==='indicator').length}if(r[3].status==='fulfilled')notificationStore.setUnreadCount(r[3].value.data);if(r[4].status==='fulfilled')mfa.value=Boolean(r[4].value.data?.enabled)}
async function logout(){try{await showConfirmDialog({title:t('profile.logout'),message:t('profile.logout_confirm')})}catch{return}try{await authApi.logout()}finally{userStore.logout();router.replace('/login')}}
async function loadPurchases(){let page=1,items=[],total=0;do{const d=(await marketApi.getMyPurchases({page,page_size:50})).data;const batch=d?.items||[];total=Number(d?.total||0);items.push(...batch);if(!batch.length)break;page++}while(items.length<total);return {data:{items,total}}}
function handleMenu(item){router.push(item.path)} function formatNumber(v){return Number(v||0).toLocaleString()} function onAvatarError(e){if(e?.target)e.target.src=logoUrl}
</script>

<style scoped>
.profile-page{padding-top:calc(26px + var(--safe-area-top))}.identity{display:grid;grid-template-columns:58px 1fr;gap:13px;align-items:center;margin:22px 2px 14px}.identity img{width:58px;height:58px;border-radius:50%;object-fit:cover;background:color-mix(in srgb,var(--v2-brand) 20%,var(--v2-surface))}.identity h2{margin:0;font-size:20px}.identity h2 span{display:inline-flex;align-items:center;gap:4px;margin-left:7px;padding:5px 10px;border-radius:99px;background:color-mix(in srgb,var(--v2-brand) 32%,var(--v2-surface));font-size:11px;font-weight:600}.identity p{margin:5px 0 0;color:var(--v2-muted);font-size:14px}.stats{display:grid;grid-template-columns:repeat(3,1fr);padding:13px 0}.stats button{min-height:54px;border:0;background:transparent;color:var(--v2-text)}.stats button+button{border-left:1px solid var(--v2-line)}.stats span,.stats strong{display:block}.stats span{color:var(--v2-muted);font-size:11px}.stats strong{margin-top:5px;font-size:23px}.account{width:100%;display:grid;grid-template-columns:48px 1fr auto;gap:12px;align-items:center;margin-top:10px;padding:13px;color:var(--v2-text);text-align:left}.exchange{width:48px;height:48px;display:grid;place-items:center;border-radius:50%;background:var(--v2-brand);color:white;font-size:28px;font-weight:900}.account>span:nth-child(2){min-width:0}.account strong,.account b,.account small{display:block}.account strong{font-size:16px}.account b{margin-top:3px;font-size:12px;font-weight:500}.account em{color:var(--v2-green);font-style:normal}.account small{margin-top:3px;color:var(--v2-muted)}.menu-block h2{margin:17px 2px 7px;color:var(--v2-muted);font-size:13px;font-weight:500}.menu-list{overflow:hidden}.menu-list button{width:100%;height:50px;display:grid;grid-template-columns:31px 1fr auto auto;gap:8px;align-items:center;padding:0 13px;border:0;border-bottom:1px solid var(--v2-line);background:transparent;color:var(--v2-text);text-align:left}.menu-list button:last-child{border-bottom:0}.menu-list button>.van-icon:first-child{font-size:22px}.menu-list span{font-size:14px}.menu-list em{color:var(--v2-muted);font-size:12px;font-style:normal}.menu-list button>.van-icon:last-child{color:var(--v2-muted)}
</style>

<style scoped>
.profile-top{position:absolute;top:calc(16px + var(--safe-area-top));right:16px;display:flex;justify-content:flex-end}.profile-page{position:relative;padding-top:calc(16px + var(--safe-area-top))}.identity{min-height:58px;margin:0 54px 18px 2px;grid-template-columns:58px minmax(0,1fr)}.identity h2,.identity p{overflow-wrap:anywhere}.profile-notifications{position:relative;display:grid;place-items:center;width:42px;height:42px;border:0;border-radius:12px;background:transparent;color:var(--v2-text);font-size:23px}.profile-notifications span{position:absolute;top:-3px;right:-3px;min-width:17px;padding:1px 4px;border-radius:10px;background:var(--v2-brand);color:var(--v2-on-brand);font-size:10px}.logout-button{margin-top:24px;border-radius:10px;height:46px}
</style>
