const keys = ['loadFailed','unknown','orders','aiFilter','decisions','radar','cancelOrder','confirmCancel','noData','allStrategies','realized','unrealized','updated','source','fullscreen','exitFullscreen','noIndicators','browseIndicators','accountChanged','invalidRisk','insufficientBalance','orderReview','riskUnknown','periodReturn','signalMode','liveMode','paperMode','buySpot','sellSpot','loading','report','noAccount','refresh','all','tracked','trackedHint','stale','nextPage','previousPage','sourceChanged','acceptSourceChange','noLive']
const rows = {
  'zh-CN': ['加载失败，请重试','未提供','当前委托','AI 决策过滤','AI 决策','事件雷达','撤单','确认撤销此委托？','暂无数据','全部策略','已实现盈亏','未实现盈亏','更新于 {time}','行情来源','全屏图表','退出全屏','还没有可运行的指标','浏览指标','账户或交易标的已变化，请重新确认','请检查止盈止损价格与交易方向','金额超过可用余额','{account}\n{symbol} · {market}\n{side} · {type}\n金额：{amount} USDT\n价格：{price}\n杠杆：{leverage}x · {margin}\n止盈：{tp} · 止损：{sl}','风险数据未提供','历史收益','信号模式','实盘','模拟','买入','卖出','加载中','分析报告','连接交易账户','刷新','全部持仓','仅闪电记录部分','仅按闪电交易已成交记录估算可平数量，交易所手动交易可能影响结果。','数据未更新，请刷新后重试','下一页','上一页',"策略源的配置已变更：原部署 {before}；当前版本 {after}。保存将采用当前版本，请先核对。","我已核对并确认采用当前版本","还没有实盘策略"],
  'zh-TW': ['載入失敗，請重試','未提供','目前委託','AI 決策過濾','AI 決策','事件雷達','撤單','確認撤銷此委託？','暫無資料','全部策略','已實現盈虧','未實現盈虧','更新於 {time}','行情來源','全螢幕圖表','退出全螢幕','還沒有可執行的指標','瀏覽指標','帳戶或交易標的已變更，請重新確認','請檢查停利停損價格與交易方向','金額超過可用餘額','{account}\n{symbol} · {market}\n{side} · {type}\n金額：{amount} USDT\n價格：{price}\n槓桿：{leverage}x · {margin}\n停利：{tp} · 停損：{sl}','未提供風險資料','歷史收益','訊號模式','實盤','模擬','買入','賣出','載入中','分析報告','連接交易帳戶','重新整理','全部持倉','僅閃電紀錄部分','僅依閃電交易成交紀錄估算可平數量，交易所手動交易可能影響結果。','資料未更新，請重新整理後重試','下一頁','上一頁',"策略來源的設定已變更：原部署 {before}；目前版本 {after}。儲存將採用目前版本，請先核對。","我已核對並確認採用目前版本","還沒有實盤策略"],
  'en-US': ['Unable to load. Please retry.','Not available','Open orders','AI decision filter','AI decisions','Event radar','Cancel order','Cancel this order?','No data yet','All strategies','Realized P&L','Unrealized P&L','Updated {time}','Price source','Full-screen chart','Exit full screen','No indicators available','Browse indicators','Account or symbol changed. Review the order again.','Check TP/SL prices against the order direction.','Amount exceeds available balance','{account}\n{symbol} · {market}\n{side} · {type}\nAmount: {amount} USDT\nPrice: {price}\nLeverage: {leverage}x · {margin}\nTP: {tp} · SL: {sl}','Risk data unavailable','Historical return','Signals','Live','Paper','Buy','Sell','Loading','Analysis report','Connect an account','Refresh','All positions','Quick Trade only','Closing size is estimated from filled Quick Trade records. Manual exchange trades may affect it.','Data is stale. Refresh before retrying.','Next page','Previous page',"The strategy source changed: deployed {before}; current {after}. Saving will use the current version. Review the changes first.","I reviewed and accept the current version","No live strategies yet"],
  'ja-JP': ['読み込みに失敗しました。再試行してください','未提供','未約定注文','AI 判断フィルター','AI 判断','イベントレーダー','注文取消','この注文を取り消しますか？','データなし','すべての戦略','確定損益','評価損益','更新 {time}','価格配信元','全画面チャート','全画面を終了','利用可能な指標がありません','指標を見る','口座または銘柄が変更されました。注文を再確認してください','利確・損切価格と売買方向を確認してください','利用可能残高を超えています','{account}\n{symbol} · {market}\n{side} · {type}\n金額：{amount} USDT\n価格：{price}\nレバレッジ：{leverage}x · {margin}\n利確：{tp} · 損切：{sl}','リスクデータなし','過去の収益','シグナル','実取引','デモ','買い','売り','読み込み中','分析レポート','取引口座を接続','更新','全ポジション','クイック取引のみ','クイック取引の約定記録から決済数量を推定します。取引所での手動売買により差が生じます。','データが古いため更新してください','次のページ','前のページ',"戦略の設定が変更されています。稼働時：{before}、現在：{after}。保存すると現在の設定が適用されます。","変更を確認し、現在の設定を使用します","実取引戦略はまだありません"],
  'ko-KR': ['불러오지 못했습니다. 다시 시도하세요','제공되지 않음','미체결 주문','AI 판단 필터','AI 판단','이벤트 레이더','주문 취소','이 주문을 취소할까요?','데이터 없음','모든 전략','실현 손익','미실현 손익','업데이트 {time}','시세 제공처','전체 화면 차트','전체 화면 종료','사용 가능한 지표가 없습니다','지표 둘러보기','계좌 또는 종목이 변경되었습니다. 주문을 다시 확인하세요','익절·손절 가격과 주문 방향을 확인하세요','사용 가능한 잔액을 초과했습니다','{account}\n{symbol} · {market}\n{side} · {type}\n금액: {amount} USDT\n가격: {price}\n레버리지: {leverage}x · {margin}\n익절: {tp} · 손절: {sl}','위험 데이터 없음','과거 수익','신호','실거래','모의','매수','매도','불러오는 중','분석 보고서','거래 계좌 연결','새로고침','전체 포지션','빠른 거래 기록만','빠른 거래 체결 기록으로 청산 수량을 추정합니다. 거래소 수동 거래의 영향을 받을 수 있습니다.','데이터가 오래되었습니다. 새로고침하세요','다음 페이지','이전 페이지',"전략 설정이 변경되었습니다. 배포 시: {before}, 현재: {after}. 저장하면 현재 설정이 적용됩니다.","변경을 확인하고 현재 설정을 적용합니다","실거래 전략이 없습니다"]
}
const parameterNames = ['target_pct','allow_short','fast_period','slow_period','stop_loss_pct','take_profit_pct']
const parameterLabels = {
  'zh-CN': ['目标仓位比例','允许做空','快线周期','慢线周期','止损比例','止盈比例'],
  'zh-TW': ['目標倉位比例','允許做空','快線週期','慢線週期','停損比例','停利比例'],
  'en-US': ['Target position ratio','Allow short selling','Fast period','Slow period','Stop-loss ratio','Take-profit ratio'],
  'ja-JP': ['目標ポジション比率','空売りを許可','短期の期間','長期の期間','損切り比率','利確比率'],
  'ko-KR': ['목표 포지션 비율','공매도 허용','단기 기간','장기 기간','손절 비율','익절 비율']
}
const featureNames = ['backtest','ai_review','ai_analysis','ai_code_gen','ai_copilot_chat','ai_copilot_image','ai_decision_filter','event_radar']
const featureLabels = {
  'zh-CN': ['策略回测','AI 策略评审','AI 投研分析','AI 策略生成','AI 对话','AI 图片分析','AI 决策过滤','事件雷达分析'],
  'zh-TW': ['策略回測','AI 策略評審','AI 投研分析','AI 策略生成','AI 對話','AI 圖片分析','AI 決策過濾','事件雷達分析'],
  'en-US': ['Strategy backtest','AI strategy review','AI research','AI strategy generation','AI chat','AI image analysis','AI decision filter','Event radar analysis'],
  'ja-JP': ['戦略バックテスト','AI 戦略レビュー','AI 市場分析','AI 戦略生成','AI チャット','AI 画像分析','AI 判断フィルター','イベント分析'],
  'ko-KR': ['전략 백테스트','AI 전략 검토','AI 시장 분석','AI 전략 생성','AI 채팅','AI 이미지 분석','AI 판단 필터','이벤트 분석']
}
export default Object.fromEntries(Object.entries(rows).map(([locale, values]) => [locale, {...Object.fromEntries(keys.map((key, index) => [key, values[index]])),features:Object.fromEntries(featureNames.map((name,index)=>[name,featureLabels[locale][index]])),params:Object.fromEntries(parameterNames.map((name,index)=>[name,parameterLabels[locale][index]]))}]))
