const zhTW = {
  'indicator_chart.updated_at': '更新於 {time}', 'indicator_chart.signal_buy': '做多訊號', 'indicator_chart.signal_sell': '做空訊號', 'indicator_chart.signal_neutral': '狀態訊號', 'indicator_chart.param_atr_period': 'ATR 週期', 'indicator_chart.param_multiplier': 'ATR 倍數', 'indicator_chart.param_period': '週期', 'indicator_chart.param_fast_period': '快線週期', 'indicator_chart.param_slow_period': '慢線週期', 'indicator_chart.param_signal_period': '訊號週期', 'indicator_chart.drag_hint': '拖曳查看歷史', 'indicator_chart.zoom_out': '顯示更多 K 線', 'indicator_chart.zoom_in': '放大', 'indicator_chart.reset_view': '返回最新行情', 'indicator_chart.latest': '最新', 'indicator_chart.selected_candle': '所選 K 線', 'indicator_chart.latest_candle': '最新 K 線', 'indicator_chart.signals_short': '訊號',
  'trading.status_filter': '策略狀態篩選', 'trading.sort_attention': '需要處理', 'trading.sort_recent': '最近更新', 'trading.sort_name': '名稱', 'trading.stopped_position_attention': '已停止的策略仍有持倉或待處理訂單', 'trading.account_requires_attention': '實盤策略需要執行帳戶', 'trading.strategy_run_error': '最近一次運行回報錯誤', 'trading.stopped_with_positions': '策略已停止，但仍有 {count} 個持倉', 'trading.stopped_with_positions_desc': '停止策略不會自動平倉，請先檢查並處理目前持倉。', 'trading.attention_items': '需要處理', 'trading.position_requires_attention': '目前持倉已不再由此策略管理', 'trading.view_positions': '查看持倉', 'trading.view_events': '查看事件', 'trading.no_attention_items': '目前沒有需要處理的事項', 'trading.runtime_overview': '運行概覽', 'trading.current_positions': '目前持倉', 'trading.recent_trades': '最近成交', 'trading.last_signal': '最新事件', 'trading.last_updated': '最後更新', 'trading.no_recent_event': '暫無最近事件', 'trading.technical_details': '技術詳情', 'trading.handle_positions': '檢查持倉', 'trading.restart_with_position_title': '重新啟動此策略？', 'trading.restart_with_position_msg': '目前有 {count} 個持倉或待處理訂單。重新啟動後可能會恢復管理，請先確認帳戶與參數。', 'trading.delete_blocked_exposure': '有持倉或待處理訂單的策略無法刪除', 'trading.event_open_long': '偵測到做多訊號', 'trading.event_open_short': '偵測到做空訊號', 'trading.event_close_long': '偵測到平多訊號', 'trading.event_close_short': '偵測到平空訊號', 'trading.event_order_pending': '訂單等待處理', 'trading.event_run_error': '策略運行回報錯誤', 'trading.create_source_search': '搜尋策略名稱或說明', 'trading.create_source_filter': '策略類型篩選', 'trading.create_source_filter_empty': '沒有符合篩選條件的策略', 'trading.recently_used': '最近使用',
  'ai_analysis.risk_reward': '盈虧比', 'ai_analysis.rr_final_hint': '最終進場、停損與目標', 'ai_analysis.rr_warning_title': '盈虧比低於 1', 'ai_analysis.rr_warning_desc': '潛在收益低於預計風險，系統不會自動拉高目標價。',
  'market.asset_type_label': '資產類型', 'market.clear_filters': '清除篩選', 'market.view_my_strategies': '查看我的策略', 'market.empty_load_title': '市場暫時無法使用', 'market.empty_load_desc': '請檢查網路連線後重新整理。', 'market.empty_filter_title': '沒有符合的結果', 'market.empty_filter_desc': '清除搜尋或價格篩選後再試。', 'market.empty_strategy_title': '新策略即將上線', 'market.empty_strategy_desc': '目前尚未上架策略，你可以先管理既有策略。', 'market.empty_indicator_title': '新指標即將上線', 'market.empty_indicator_desc': '目前尚未上架指標，請稍後重新整理。',
  'script_strategy.customer_desc': '適合在手機端直接設定與運行的策略。',
  'credentials.status_connected': '已連線', 'credentials.status_check': '需要檢查', 'credentials.last_checked': '最後檢查：{time}',
  'notifications.category_filter': '通知分類', 'notifications.category_all': '全部', 'notifications.category_alert': '風險', 'notifications.category_trade': '訂單', 'notifications.category_signal': '訊號', 'notifications.category_system': '系統', 'notifications.merged_count': '已合併 {count} 則', 'notifications.default_signal_title': '策略訊號', 'notifications.default_trade_title': '訂單更新', 'notifications.default_alert_title': '風險提醒', 'notifications.default_system_title': '系統通知', 'notifications.action_open_long': '{symbol} 做多訊號', 'notifications.action_open_short': '{symbol} 做空訊號', 'notifications.action_add_long': '{symbol} 加多訊號', 'notifications.action_add_short': '{symbol} 加空訊號', 'notifications.action_close_long': '{symbol} 平多訊號', 'notifications.action_close_short': '{symbol} 平空訊號', 'notifications.action_label_open_long': '做多', 'notifications.action_label_open_short': '做空', 'notifications.action_label_add_long': '加多', 'notifications.action_label_add_short': '加空', 'notifications.action_label_close_long': '平多', 'notifications.action_label_close_short': '平空', 'notifications.signal_detected': '{symbol} 產生了{action}訊號，操作前請先檢查行情。', 'notifications.signal_closed': '{symbol} 產生了{action}訊號。', 'notifications.risk_requires_attention': '有一項風險狀況需要處理，請開啟詳情檢查。', 'notifications.the_strategy': '此策略', 'notifications.view_strategy': '查看策略', 'notifications.technical_details': '技術詳情'
}

const jaJP = {
  'indicator_chart.updated_at': '{time} に更新', 'indicator_chart.signal_buy': 'ロングシグナル', 'indicator_chart.signal_sell': 'ショートシグナル', 'indicator_chart.signal_neutral': '状態シグナル', 'indicator_chart.param_atr_period': 'ATR期間', 'indicator_chart.param_multiplier': 'ATR倍率', 'indicator_chart.param_period': '期間', 'indicator_chart.param_fast_period': '短期期間', 'indicator_chart.param_slow_period': '長期期間', 'indicator_chart.param_signal_period': 'シグナル期間', 'indicator_chart.drag_hint': 'ドラッグして履歴を表示', 'indicator_chart.zoom_out': 'ローソク足をさらに表示', 'indicator_chart.zoom_in': '拡大', 'indicator_chart.reset_view': '最新の相場へ戻る', 'indicator_chart.latest': '最新', 'indicator_chart.selected_candle': '選択したローソク足', 'indicator_chart.latest_candle': '最新のローソク足', 'indicator_chart.signals_short': 'シグナル',
  'trading.status_filter': '戦略ステータス', 'trading.sort_attention': '要確認', 'trading.sort_recent': '更新順', 'trading.sort_name': '名前', 'trading.stopped_position_attention': '停止した戦略にポジションまたは保留注文があります', 'trading.account_requires_attention': '実運用戦略には取引口座が必要です', 'trading.strategy_run_error': '直近の実行でエラーが報告されました', 'trading.stopped_with_positions': '戦略は停止中ですが、{count} 件のポジションがあります', 'trading.stopped_with_positions_desc': '戦略を停止しても自動決済されません。続行前にポジションを確認してください。', 'trading.attention_items': '要確認', 'trading.position_requires_attention': '現在のポジションはこの戦略で管理されていません', 'trading.view_positions': 'ポジションを見る', 'trading.view_events': 'イベントを見る', 'trading.no_attention_items': '確認が必要な項目はありません', 'trading.runtime_overview': '運用概要', 'trading.current_positions': '保有ポジション', 'trading.recent_trades': '最近の取引', 'trading.last_signal': '最新イベント', 'trading.last_updated': '最終更新', 'trading.no_recent_event': '最近のイベントはありません', 'trading.technical_details': '技術詳細', 'trading.handle_positions': 'ポジションを確認', 'trading.restart_with_position_title': 'この戦略を再開しますか？', 'trading.restart_with_position_msg': '{count} 件のポジションまたは保留注文があります。再開すると管理を再開する場合があります。先に口座とパラメータを確認してください。', 'trading.delete_blocked_exposure': 'ポジションまたは保留注文がある戦略は削除できません', 'trading.event_open_long': 'ロングシグナルを検出', 'trading.event_open_short': 'ショートシグナルを検出', 'trading.event_close_long': 'ロング決済シグナルを検出', 'trading.event_close_short': 'ショート決済シグナルを検出', 'trading.event_order_pending': '注文は処理待ちです', 'trading.event_run_error': '戦略の実行でエラーが報告されました', 'trading.create_source_search': '戦略名または説明を検索', 'trading.create_source_filter': '戦略タイプ', 'trading.create_source_filter_empty': '条件に一致する戦略がありません', 'trading.recently_used': '最近使用',
  'ai_analysis.risk_reward': 'リスクリワード', 'ai_analysis.rr_final_hint': '最終エントリー、損切り、目標', 'ai_analysis.rr_warning_title': 'リスクリワードが1未満です', 'ai_analysis.rr_warning_desc': '想定利益が計画リスクを下回っています。目標価格は自動で引き上げられません。',
  'market.asset_type_label': '資産タイプ', 'market.clear_filters': 'フィルターを解除', 'market.view_my_strategies': 'マイ戦略を見る', 'market.empty_load_title': 'マーケットを一時的に利用できません', 'market.empty_load_desc': '接続を確認して更新してください。', 'market.empty_filter_title': '一致する結果がありません', 'market.empty_filter_desc': '検索または価格フィルターを解除してお試しください。', 'market.empty_strategy_title': '新しい戦略を準備中です', 'market.empty_strategy_desc': '現在掲載中の戦略はありません。既存の戦略は管理できます。', 'market.empty_indicator_title': '新しい指標を準備中です', 'market.empty_indicator_desc': '現在掲載中の指標はありません。後でもう一度更新してください。',
  'script_strategy.customer_desc': 'モバイルですぐに設定して運用できる戦略です。',
  'credentials.status_connected': '接続済み', 'credentials.status_check': '要確認', 'credentials.last_checked': '最終確認：{time}',
  'notifications.category_filter': '通知カテゴリー', 'notifications.category_all': 'すべて', 'notifications.category_alert': 'リスク', 'notifications.category_trade': '注文', 'notifications.category_signal': 'シグナル', 'notifications.category_system': 'システム', 'notifications.merged_count': '{count} 件を統合', 'notifications.default_signal_title': '戦略シグナル', 'notifications.default_trade_title': '注文更新', 'notifications.default_alert_title': 'リスクアラート', 'notifications.default_system_title': 'システム通知', 'notifications.action_open_long': '{symbol} ロングシグナル', 'notifications.action_open_short': '{symbol} ショートシグナル', 'notifications.action_add_long': '{symbol} ロング追加シグナル', 'notifications.action_add_short': '{symbol} ショート追加シグナル', 'notifications.action_close_long': '{symbol} ロング決済シグナル', 'notifications.action_close_short': '{symbol} ショート決済シグナル', 'notifications.action_label_open_long': 'ロング', 'notifications.action_label_open_short': 'ショート', 'notifications.action_label_add_long': 'ロング追加', 'notifications.action_label_add_short': 'ショート追加', 'notifications.action_label_close_long': 'ロング決済', 'notifications.action_label_close_short': 'ショート決済', 'notifications.signal_detected': '{symbol} で{action}シグナルが発生しました。操作前に相場を確認してください。', 'notifications.signal_closed': '{symbol} で{action}シグナルが発生しました。', 'notifications.risk_requires_attention': '確認が必要なリスクがあります。詳細を開いて確認してください。', 'notifications.the_strategy': 'この戦略', 'notifications.view_strategy': '戦略を見る', 'notifications.technical_details': '技術詳細'
}

const koKR = {
  'indicator_chart.updated_at': '{time} 업데이트', 'indicator_chart.signal_buy': '롱 신호', 'indicator_chart.signal_sell': '숏 신호', 'indicator_chart.signal_neutral': '상태 신호', 'indicator_chart.param_atr_period': 'ATR 기간', 'indicator_chart.param_multiplier': 'ATR 배수', 'indicator_chart.param_period': '기간', 'indicator_chart.param_fast_period': '단기 기간', 'indicator_chart.param_slow_period': '장기 기간', 'indicator_chart.param_signal_period': '신호 기간', 'indicator_chart.drag_hint': '드래그하여 과거 보기', 'indicator_chart.zoom_out': '더 많은 캔들 보기', 'indicator_chart.zoom_in': '확대', 'indicator_chart.reset_view': '최신 시세로 돌아가기', 'indicator_chart.latest': '최신', 'indicator_chart.selected_candle': '선택한 캔들', 'indicator_chart.latest_candle': '최신 캔들', 'indicator_chart.signals_short': '신호',
  'trading.status_filter': '전략 상태 필터', 'trading.sort_attention': '확인 필요', 'trading.sort_recent': '최근 업데이트', 'trading.sort_name': '이름', 'trading.stopped_position_attention': '중지된 전략에 포지션 또는 대기 주문이 있습니다', 'trading.account_requires_attention': '실거래 전략에는 실행 계정이 필요합니다', 'trading.strategy_run_error': '최근 실행에서 오류가 보고되었습니다', 'trading.stopped_with_positions': '전략이 중지되었지만 {count}개의 포지션이 있습니다', 'trading.stopped_with_positions_desc': '전략을 중지해도 포지션은 자동 청산되지 않습니다. 계속하기 전에 확인하세요.', 'trading.attention_items': '확인 필요', 'trading.position_requires_attention': '현재 포지션은 더 이상 이 전략에서 관리되지 않습니다', 'trading.view_positions': '포지션 보기', 'trading.view_events': '이벤트 보기', 'trading.no_attention_items': '확인할 항목이 없습니다', 'trading.runtime_overview': '실행 개요', 'trading.current_positions': '보유 포지션', 'trading.recent_trades': '최근 거래', 'trading.last_signal': '최신 이벤트', 'trading.last_updated': '마지막 업데이트', 'trading.no_recent_event': '최근 이벤트가 없습니다', 'trading.technical_details': '기술 세부정보', 'trading.handle_positions': '포지션 확인', 'trading.restart_with_position_title': '이 전략을 다시 시작할까요?', 'trading.restart_with_position_msg': '{count}개의 포지션 또는 대기 주문이 있습니다. 다시 시작하면 관리가 재개될 수 있습니다. 먼저 계정과 설정을 확인하세요.', 'trading.delete_blocked_exposure': '포지션 또는 대기 주문이 있는 전략은 삭제할 수 없습니다', 'trading.event_open_long': '롱 신호 감지', 'trading.event_open_short': '숏 신호 감지', 'trading.event_close_long': '롱 청산 신호 감지', 'trading.event_close_short': '숏 청산 신호 감지', 'trading.event_order_pending': '주문 처리 대기 중', 'trading.event_run_error': '전략 실행 오류가 보고되었습니다', 'trading.create_source_search': '전략 이름 또는 설명 검색', 'trading.create_source_filter': '전략 유형 필터', 'trading.create_source_filter_empty': '필터와 일치하는 전략이 없습니다', 'trading.recently_used': '최근 사용',
  'ai_analysis.risk_reward': '손익비', 'ai_analysis.rr_final_hint': '최종 진입가, 손절가 및 목표가', 'ai_analysis.rr_warning_title': '손익비가 1 미만입니다', 'ai_analysis.rr_warning_desc': '예상 수익이 계획한 위험보다 낮습니다. 목표가는 자동으로 늘어나지 않습니다.',
  'market.asset_type_label': '자산 유형', 'market.clear_filters': '필터 지우기', 'market.view_my_strategies': '내 전략 보기', 'market.empty_load_title': '마켓을 일시적으로 사용할 수 없습니다', 'market.empty_load_desc': '연결을 확인하고 새로고침하세요.', 'market.empty_filter_title': '일치하는 결과가 없습니다', 'market.empty_filter_desc': '검색 또는 가격 필터를 지우고 다시 시도하세요.', 'market.empty_strategy_title': '새 전략을 준비 중입니다', 'market.empty_strategy_desc': '현재 등록된 전략이 없습니다. 기존 전략은 관리할 수 있습니다.', 'market.empty_indicator_title': '새 지표를 준비 중입니다', 'market.empty_indicator_desc': '현재 등록된 지표가 없습니다. 나중에 다시 새로고침하세요.',
  'script_strategy.customer_desc': '모바일에서 바로 설정하고 실행할 수 있는 전략입니다.',
  'credentials.status_connected': '연결됨', 'credentials.status_check': '확인 필요', 'credentials.last_checked': '마지막 확인: {time}',
  'notifications.category_filter': '알림 카테고리', 'notifications.category_all': '전체', 'notifications.category_alert': '위험', 'notifications.category_trade': '주문', 'notifications.category_signal': '신호', 'notifications.category_system': '시스템', 'notifications.merged_count': '{count}개 통합', 'notifications.default_signal_title': '전략 신호', 'notifications.default_trade_title': '주문 업데이트', 'notifications.default_alert_title': '위험 알림', 'notifications.default_system_title': '시스템 알림', 'notifications.action_open_long': '{symbol} 롱 신호', 'notifications.action_open_short': '{symbol} 숏 신호', 'notifications.action_add_long': '{symbol} 롱 추가 신호', 'notifications.action_add_short': '{symbol} 숏 추가 신호', 'notifications.action_close_long': '{symbol} 롱 청산 신호', 'notifications.action_close_short': '{symbol} 숏 청산 신호', 'notifications.action_label_open_long': '롱', 'notifications.action_label_open_short': '숏', 'notifications.action_label_add_long': '롱 추가', 'notifications.action_label_add_short': '숏 추가', 'notifications.action_label_close_long': '롱 청산', 'notifications.action_label_close_short': '숏 청산', 'notifications.signal_detected': '{symbol}에서 {action} 신호가 발생했습니다. 실행 전에 시장을 확인하세요.', 'notifications.signal_closed': '{symbol}에서 {action} 신호가 발생했습니다.', 'notifications.risk_requires_attention': '확인이 필요한 위험 상태가 있습니다. 세부정보를 열어 확인하세요.', 'notifications.the_strategy': '이 전략', 'notifications.view_strategy': '전략 보기', 'notifications.technical_details': '기술 세부정보'
}

export default { 'zh-TW': zhTW, 'ja-JP': jaJP, 'ko-KR': koKR }
