const en = {
  title: 'Evidence & data-quality audit', professional_tier: 'Professional data', community_tier: 'Community data',
  contract_required: 'This is an obsolete report', contract_required_desc: 'This saved result does not contain professional_report_v1. Regenerate it to view the evidence-backed format.', regenerate: 'Regenerate',
  model_strength: 'Model strength, not win rate', market_bias: 'Market bias', bias_bullish: 'Bullish', bias_bearish: 'Bearish', bias_neutral: 'Neutral', trade_action: 'Trade action', executive_summary: 'Executive summary', current_price: 'Snapshot price', price_change: 'Price change', timeframe: 'Timeframe', data_quality: 'Data quality', coverage: 'Coverage', freshness: 'Freshness', conflict: 'Conflict', conclusion_strength: 'Conclusion strength', data_as_of: 'Data as of', audit_warnings: 'Audit findings',
  direction_blocked: 'Directional conclusion blocked', direction_blocked_desc: 'Required evidence is missing, stale or conflicting, so this report has been downgraded to HOLD.', missing_data: 'Data and capability gaps', dimensions: 'Analysis dimensions', insufficient: 'Insufficient data', no_narrative: 'No evidence-backed narrative is available.',
  scenarios: 'Scenario analysis', target: 'Target', invalidation: 'Invalidation', risk_plan: 'Risk and execution plan', candidate_setup: 'Watch-only candidate setup', candidate_setup_desc: 'These reference levels explain the current decision. They are not an active entry recommendation and the recommended position remains zero.', gross_rr: 'Gross R/R', net_rr: 'Net R/R', position_cap: 'Position cap', risk_budget: 'Risk budget', cost: 'Round-trip cost', claims: 'Evidence-linked claims', evidence: 'Evidence snapshot and provenance', evidence_references: 'Evidence references', open_source: 'Open source',
  dimension: { technical: 'Technical structure', fundamental: 'Fundamentals', news_sentiment: 'News and sentiment', sentiment: 'Market sentiment', macro: 'Macro environment', market_specific: 'Market-specific factors', crypto_market_structure: 'Crypto market structure' },
  scenario: { bull: 'Bull case', base: 'Base case', bear: 'Bear case' },
  scenario_trigger: { bull: 'Price and supporting evidence confirm the upside case.', base: 'Evidence remains mixed and follows the central case.', bear: 'A downside catalyst or technical breakdown is confirmed.' },
  claim: { thesis: 'Core thesis', counter_argument: 'Counterargument', risk: 'Risk', catalyst: 'Catalyst' },
  strength: { none: 'Insufficient', low: 'Low', medium: 'Medium', high: 'High' },
  warning: { no_directional_position: 'No directional position while the conclusion is HOLD', invalid_price_geometry: 'Entry, stop and target geometry is invalid', net_risk_reward_below_one: 'Net risk/reward is below 1 after estimated costs', candidate_net_risk_reward_below_one: 'The watch-only candidate has net risk/reward below 1 after estimated costs', position_reduced_for_data_quality: 'Position cap reduced because of data quality', funding_cost_not_guaranteed: 'Funding cost may change before execution', liquidation_and_venue_risk: 'Perpetual contracts carry liquidation and venue risk', gap_risk_not_capped_by_stop: 'A stop cannot cap equity gap risk', insufficient_coverage: 'Required data coverage is incomplete', stale_data: 'Some evidence is stale', conflicting_evidence: 'Required evidence contains conflicts', invalid_evidence: 'Some evidence failed validation', no_required_metrics: 'No required metrics were available', directional_decision_blocked: 'Directional decision blocked by data quality', invalid_risk_plan: 'Risk-plan price geometry failed validation', instrument_identity_unverified: 'Instrument identity could not be verified', crypto_scope_or_unit_validation_failed: 'Crypto venue, product or unit validation failed', professional_tier_requested_but_no_professional_evidence: 'Professional data was requested but no professional evidence was available', unsupported_professional_report_market: 'This market is not supported by the professional report', financial_statements_unavailable: 'Financial statements are unavailable', market_specific_data_incomplete: 'Market-specific data is incomplete', confidence_capped: 'Confidence capped by evidence quality', claim_validation_failed: 'An unsupported claim was removed during evidence validation' },
  unit: { bps: 'bps', count: 'items', share: 'share', shares: 'shares' },
  metric_part: {
    quote: 'Quote', financial: 'Financials', latest_quarter: 'Latest quarter', latest_annual: 'Latest annual period', ttm: 'Trailing 12 months',
    balance_sheet: 'Balance sheet', cash_flow: 'Cash flow statement', income_statement: 'Income statement', derived: 'Derived metric', indicator: 'Technical indicator', macro: 'Macro', crypto: 'Crypto market', ohlcv: 'OHLCV', earnings: 'Earnings', history: 'History',
    price: 'Price', open: 'Open', high: 'High', low: 'Low', close: 'Close', volume: 'Volume', previous_close: 'Previous close', change: 'Change', change_percent: 'Change %', latest_bar: 'Latest bar', bar_count: 'Bar count',
    rsi: 'RSI', macd: 'MACD', value: 'Value', signal: 'Signal', signal_line: 'Signal line', histogram: 'Histogram', trend: 'Trend', moving_averages: 'Moving averages',
    levels: 'Key levels', support: 'Support', resistance: 'Resistance', swing_low: 'Swing low', swing_high: 'Swing high', pivot: 'Pivot', method: 'Method', kind: 'Type', is_estimate: 'Estimated value',
    bollinger: 'Bollinger Bands', bb_lower: 'Lower band', bb_middle: 'Middle band', bb_upper: 'Upper band', bb_width: 'Band width', volume_ratio: 'Volume ratio', volume_ratio_meta: 'Volume-ratio definition', baseline: 'Baseline', baseline_bars: 'Baseline bars',
    volatility: 'Volatility', atr: 'ATR', pct: 'Percentage', price_position: 'Range position', current_price: 'Current price', trading_levels: 'Trading levels', suggested_stop_loss: 'Suggested stop', suggested_take_profit: 'Suggested target', risk_reward_ratio: 'Risk/reward', atr_multiplier_sl: 'Stop ATR multiple', atr_multiplier_tp: 'Target ATR multiple',
    market_cap: 'Market capitalization', revenue_growth: 'Revenue growth', profit_margin: 'Profit margin', pe_ratio: 'P/E ratio', pb_ratio: 'P/B ratio', dividend_yield: 'Dividend yield', current_ratio: 'Current ratio', quick_ratio: 'Quick ratio', debt_to_equity: 'Debt/equity',
    total_revenue: 'Revenue', gross_profit: 'Gross profit', operating_income: 'Operating income', net_income: 'Net income', operating_cash_flow: 'Operating cash flow', financing_cash_flow: 'Financing cash flow', capital_expenditure: 'Capital expenditure', free_cash_flow: 'Free cash flow',
    total_assets: 'Total assets', total_liabilities: 'Total liabilities', total_equity: 'Total equity', current_assets: 'Current assets', current_liabilities: 'Current liabilities', cash: 'Cash', debt: 'Debt', period_end: 'Period end', period_type: 'Period type', latest_date: 'Latest date',
    currency: 'Currency', source: 'Source', name: 'Name', description: 'Description', category: 'Category', eps: 'EPS', roe: 'ROE', beta: 'Beta', book_value: 'Book value', enterprise_value: 'Enterprise value', shares_outstanding: 'Shares outstanding',
    volume_24h: '24h volume', volume_change_24h: '24h volume change', last: 'Latest value', level: 'Level', spread: 'Spread', fear_greed: 'Fear & Greed Index', dxy: 'DXY', vix: 'VIX', tnx: 'US 10Y yield', timestamp: 'Time', time: 'Timestamp'
  },
  evidence_value: {
    bearish: 'Bearish', bullish: 'Bullish', neutral: 'Neutral', bearish_alignment: 'Bearish alignment', bullish_alignment: 'Bullish alignment', strong_downtrend: 'Strong downtrend', strong_uptrend: 'Strong uptrend', uptrend: 'Uptrend',
    low: 'Low', medium: 'Medium', normal: 'Normal', greed: 'Greed', heuristic_estimate: 'Heuristic estimate', pivot_swing_bb_avg: 'Average of pivot, swing and Bollinger levels', atr_support_resistance: 'ATR-based support/resistance', previous_20_bars: 'Previous 20 bars', latest_quarter_yoy: 'Latest-quarter year-over-year', quarterly: 'Quarterly', annual: 'Annual', true: 'Yes', false: 'No'
  },
  capability: { filings: 'Regulatory filings', analyst_expectations: 'Analyst expectations', options: 'Options data', short_interest: 'Short interest', insider_activity: 'Insider activity', hkex_announcements: 'HKEX announcements', southbound_flow: 'Southbound flow', short_selling: 'Short-selling data', ccass: 'CCASS holdings', ah_premium: 'A/H premium', funding_rate: 'Funding rate', open_interest: 'Open interest', open_interest_change_24h: '24h OI change', long_short_ratio: 'Long/short ratio', liquidations: 'Liquidations', volume_24h: '24h volume', market_cap: 'Market capitalization', revenue_growth: 'Revenue growth', profit_margin: 'Profit margin', quote_price: 'Current price', quote_changepercent: 'Price change', ohlcv_latest_bar: 'Latest OHLCV bar', indicator_rsi_value: 'RSI', indicator_moving_averages_trend: 'Moving-average trend' }
}

const zhCN = {
  title: '证据与数据质量审计', professional_tier: '专业数据', community_tier: '社区数据',
  contract_required: '这是一份旧契约报告', contract_required_desc: '历史结果中没有 professional_report_v1，请重新生成后查看新版证据化报告。', regenerate: '重新生成',
  model_strength: '模型判断强度，不是胜率', market_bias: '市场方向', bias_bullish: '偏多', bias_bearish: '偏空', bias_neutral: '中性', trade_action: '交易动作', executive_summary: '执行摘要', current_price: '快照价格', price_change: '价格涨跌', timeframe: '分析周期', data_quality: '数据质量', coverage: '核心指标覆盖率', freshness: '数据新鲜度', conflict: '证据冲突率', conclusion_strength: '结论强度', data_as_of: '数据截止时间', audit_warnings: '审计发现',
  direction_blocked: '数据质量不足，已禁止方向性结论', direction_blocked_desc: '必要证据存在缺失、过期或冲突，本次报告已自动降级为观望。', missing_data: '数据与能力缺口', dimensions: '多维分析', insufficient: '数据不足', no_narrative: '暂无可由证据支持的分析文字。',
  scenarios: '情景分析', target: '目标价', invalidation: '失效条件', risk_plan: '风险与执行计划', candidate_setup: '候选观察方案', candidate_setup_desc: '这些参考价位用于解释当前判断，并非正在生效的入场建议；建议仓位仍为 0。', gross_rr: '毛风险回报比', net_rr: '扣成本风险回报比', position_cap: '建议仓位上限', risk_budget: '账户风险预算', cost: '预估往返成本', claims: '可追溯结论', evidence: '证据快照与数据来源', evidence_references: '证据引用', open_source: '打开来源',
  dimension: { technical: '技术结构', fundamental: '基本面', news_sentiment: '新闻与情绪', sentiment: '市场情绪', macro: '宏观环境', market_specific: '市场特有维度', crypto_market_structure: '加密市场结构' },
  scenario: { bull: '乐观情景', base: '基准情景', bear: '悲观情景' },
  scenario_trigger: { bull: '价格走势与支持证据共同确认乐观情景。', base: '当前证据仍然分化，维持基准路径。', bear: '下行催化因素出现，或技术形态确认破位。' },
  claim: { thesis: '核心论点', counter_argument: '反方论据', risk: '风险', catalyst: '催化因素' },
  strength: { none: '证据不足', low: '较低', medium: '中等', high: '较高' },
  warning: { no_directional_position: '结论为观望，不应建立方向性仓位', invalid_price_geometry: '入场、止损和止盈的价格关系无效', net_risk_reward_below_one: '计入预估成本后，风险回报比低于 1', candidate_net_risk_reward_below_one: '候选观察方案计入预估成本后的风险回报比低于 1', position_reduced_for_data_quality: '因数据质量不足已降低仓位上限', funding_cost_not_guaranteed: '执行前资金费率仍可能变化', liquidation_and_venue_risk: '永续合约存在强平与交易场所风险', gap_risk_not_capped_by_stop: '股票跳空风险无法由止损单完全限制', insufficient_coverage: '必要数据覆盖不完整', stale_data: '部分证据已经过期', conflicting_evidence: '必要证据之间存在冲突', invalid_evidence: '部分证据未通过有效性校验', no_required_metrics: '没有获取到必要指标', directional_decision_blocked: '数据质量不足，方向性判断已被阻止', invalid_risk_plan: '入场、止损和目标价未通过风控校验', instrument_identity_unverified: '无法验证标的身份', crypto_scope_or_unit_validation_failed: '加密数据的交易场所、产品类型或单位校验失败', professional_tier_requested_but_no_professional_evidence: '请求了专业数据，但本次没有获得专业级证据', unsupported_professional_report_market: '专业报告暂不支持该市场', financial_statements_unavailable: '财务报表数据不可用', market_specific_data_incomplete: '市场特有数据不完整', confidence_capped: '证据质量限制了判断强度', claim_validation_failed: '证据校验时已移除无法支持的论点' },
  unit: { bps: '个基点', count: '项', share: '股', shares: '股' },
  metric_part: {
    quote: '行情', financial: '财务数据', latest_quarter: '最新季度', latest_annual: '最新年度', ttm: '近十二个月', balance_sheet: '资产负债表', cash_flow: '现金流量表', income_statement: '利润表', derived: '衍生指标', indicator: '技术指标', macro: '宏观数据', crypto: '加密市场', ohlcv: 'K 线', earnings: '业绩', history: '历史记录',
    price: '价格', open: '开盘价', high: '最高价', low: '最低价', close: '收盘价', volume: '成交量', previous_close: '前收盘价', change: '价格变动', change_percent: '涨跌幅', latest_bar: '最新 K 线', bar_count: 'K 线数量',
    rsi: 'RSI', macd: 'MACD', value: '数值', signal: '信号', signal_line: '信号线', histogram: '柱状图', trend: '趋势', moving_averages: '均线', levels: '关键价位', support: '支撑位', resistance: '阻力位', swing_low: '摆动低点', swing_high: '摆动高点', pivot: '枢轴位', method: '计算方法', kind: '类型', is_estimate: '是否为估算值',
    bollinger: '布林带', bb_lower: '下轨', bb_middle: '中轨', bb_upper: '上轨', bb_width: '带宽', volume_ratio: '量比', volume_ratio_meta: '量比口径', baseline: '基准区间', baseline_bars: '基准 K 线数', volatility: '波动率', atr: 'ATR', pct: '百分比', price_position: '区间位置', current_price: '当前价格', trading_levels: '交易价位', suggested_stop_loss: '建议止损价', suggested_take_profit: '建议止盈价', risk_reward_ratio: '风险回报比', atr_multiplier_sl: '止损 ATR 倍数', atr_multiplier_tp: '止盈 ATR 倍数',
    market_cap: '总市值', revenue_growth: '营收增长', profit_margin: '净利率', pe_ratio: '市盈率', pb_ratio: '市净率', dividend_yield: '股息率', current_ratio: '流动比率', quick_ratio: '速动比率', debt_to_equity: '产权比率', total_revenue: '营业收入', gross_profit: '毛利润', operating_income: '营业利润', net_income: '净利润', operating_cash_flow: '经营活动现金流', financing_cash_flow: '融资活动现金流', capital_expenditure: '资本开支', free_cash_flow: '自由现金流',
    total_assets: '总资产', total_liabilities: '总负债', total_equity: '股东权益', current_assets: '流动资产', current_liabilities: '流动负债', cash: '现金', debt: '有息负债', period_end: '报告期末', period_type: '报告周期', latest_date: '最新日期', currency: '币种', source: '来源', name: '名称', description: '说明', category: '类别', eps: '每股收益', roe: '净资产收益率', beta: '贝塔系数', book_value: '每股账面价值', enterprise_value: '企业价值', shares_outstanding: '总股本',
    volume_24h: '24 小时成交量', volume_change_24h: '24 小时成交量变化', last: '最新值', level: '点位', spread: '利差', fear_greed: '恐惧与贪婪指数', dxy: '美元指数', vix: 'VIX 恐慌指数', tnx: '美国十年期国债收益率', timestamp: '时间', time: '时间戳'
  },
  evidence_value: {
    bearish: '看空', bullish: '看多', neutral: '中性', bearish_alignment: '空头排列', bullish_alignment: '多头排列', strong_downtrend: '强势下跌', strong_uptrend: '强势上涨', uptrend: '上升趋势', low: '低', medium: '中等', normal: '正常', greed: '贪婪', heuristic_estimate: '启发式估算', pivot_swing_bb_avg: '枢轴位、摆动点和布林带均值', atr_support_resistance: '基于 ATR 的支撑阻力', previous_20_bars: '此前 20 根 K 线', latest_quarter_yoy: '最新季度同比', quarterly: '季度', annual: '年度', true: '是', false: '否'
  },
  capability: { filings: '监管申报文件', analyst_expectations: '分析师预期', options: '期权数据', short_interest: '卖空仓位', insider_activity: '内部人交易', hkex_announcements: '港交所公告', southbound_flow: '南向资金', short_selling: '卖空成交数据', ccass: '中央结算持仓', ah_premium: 'A/H 股溢价', funding_rate: '资金费率', open_interest: '未平仓合约', open_interest_change_24h: '未平仓合约 24 小时变化', long_short_ratio: '多空账户比', liquidations: '强平数据', volume_24h: '24 小时成交量', market_cap: '总市值', revenue_growth: '营收增长', profit_margin: '净利率', quote_price: '当前价格', quote_changepercent: '价格涨跌', ohlcv_latest_bar: '最新行情 K 线', indicator_rsi_value: 'RSI 指标', indicator_moving_averages_trend: '均线趋势' }
}

const zhTW = { ...zhCN, title: '證據與資料品質審核', professional_tier: '專業資料', community_tier: '社群資料', data_quality: '資料品質', missing_data: '資料與能力缺口', regenerate: '重新產生' }

export default { 'en-US': en, 'zh-CN': zhCN, 'zh-TW': zhTW, 'ja-JP': en, 'ko-KR': en }
