const zhCN = {
  nav: { strategy: '首页', live: '运行', research: 'AI投研', indicator: '指标', profile: '我的' },
  common: { notifications: '消息', createStrategy: '运行策略', retry: '重新加载', loading: '正在加载', more: '查看更多', today: '今日', cumulative: '累计', account: '账户', settings: '设置' },
  strategy: {
    title: '策略', subtitle: '选择合适的策略，让投资更简单', featured: '精选', mine: '我的策略', preferenceTitle: '你更看重什么？', stable: '稳一点', stableDesc: '追求稳健，控制回撤', balanced: '均衡', balancedDesc: '攻守兼顾', active: '更积极', activeDesc: '追求更高收益',
    recommended: '新手首选', spot: '现货', riskLow: '低风险', riskMedium: '中风险', riskHigh: '高风险', return: '历史收益', drawdown: '最大回撤', users: '{count} 人正在使用',
    simulate: '先模拟体验', details: '查看详情', moreTitle: '更多适合新手的策略', emptyTitle: '暂时没有匹配的策略', emptyDesc: '换一个偏好，或者稍后再来看看。',
    mineEmptyTitle: '还没有自己的策略', mineEmptyDesc: '从精选模板开始，不需要写代码。', mineAction: '去选策略', runNow: '连接实盘', statusRunning: '运行中', statusStopped: '已停止', statusError: '需处理',
    fallbackName: 'BTC 趋势跟随', fallbackDesc: '适合震荡后出现趋势的行情', secondName: 'ETH 低频网格', secondDesc: '震荡行情中自动低买高卖', thirdName: '多币种稳健轮动', thirdDesc: '在主流币之间分散配置', yearReturn: '近1年收益', viewAll: '查看全部策略', cost: '费用', free: '免费',
    marketTitle: '策略市场', search: '搜索策略', welcomeEyebrow: '开源AI Trading OS', welcomeTitle: '欢迎来到 QuantDinger', welcomeSubtitle: '发现经过数据验证的策略，关注你在意的市场。', riskPreference: '选择适合你的风险偏好', stableRanking: '按最大回撤从低到高排序', balancedRanking: '按收益回撤比与市场热度综合排序', activeRanking: '按历史收益与市场热度综合排序', popularRanking: '热门策略排名', viewMore: '查看更多', statisticsPeriod: '统计周期', backtestSamples: '回测样本', returnDrawdownRatio: '收益回撤比', winRate: '胜率', sharpeRatio: '夏普比率', profitLossRatio: '盈亏比', updated: '更新于', performanceNotice: '历史表现不代表未来收益', watchlistTitle: '我的自选', watchlistSubtitle: '关注标的的最新行情', manageWatchlist: '管理自选', watchlistAsset: '标的', watchlistPrice: '最新价', watchlistChange: '24小时涨跌', watchlistEmpty: '还没有自选标的', watchlistEmptyDesc: '添加常看的标的，行情变化随时掌握。', addWatchlist: '添加自选', dataRiskTitle: '数据与风控', unifiedBacktest: '统一回测口径', unifiedBacktestDesc: '便于横向比较', riskComplete: '风险指标完整', riskCompleteDesc: '收益与回撤同看', tradeConfirm: '实盘前二次确认', tradeConfirmDesc: '核对账户与参数', myRuntime: '我的运行', runningCount: '运行中', attentionCount: '待处理', unnamed: '未命名策略', marketUnknown: '市场信息待补充'
  },
  live: {
    title: '策略运行', subtitle: '统一查看策略状态、盈亏和运行健康。', console: '运行中心', attention: '{count} 个问题需要处理', attentionDesc: '有策略或账户状态异常，请尽快确认。', view: '立即处理',
    todayPnl: '今日盈亏', totalPnl: '累计盈亏', running: '运行中', total: '全部策略', positions: '持仓', sectionRunning: '运行中的策略', sectionAttention: '需要处理', sectionStopped: '已停止',
    noRunning: '暂无运行中的策略', noRunningDesc: '从策略页选择模板并连接交易账户。', chooseStrategy: '选择策略', updated: '刚刚更新', accountIssue: '交易账户需要重新连接',
    viewDetails: '查看运行详情', profit: '浮动盈亏', capital: '策略资金', status: '状态', start: '启动', pause: '暂停', attentionShort: 'ETH 网格账户余额不足', strategyUnit: '个策略', drawdown: '当前回撤', balanceLow: '可用余额低于安全线', handle: '处理', long: '多仓', readyCount: '准备启动 {count}',
    systemHealthy: '运行数据正常', systemDegraded: '部分数据加载失败', strategyCount: '{count} 个策略', requiresReview: '待检查', allClear: '状态正常', modeFilter: '执行模式', statusFilter: '运行状态', searchPlaceholder: '搜索策略、标的或交易所', clearSearch: '清除搜索', noMatches: '没有符合条件的策略', updatedAt: '{time} 更新', health_degraded: '运行异常', health_stale: '数据延迟', health_offline: '已离线', health_attention: '需处理', spotMarket: '现货', swapMarket: '永续', strategyRuntime: '策略运行', pendingOrders: '{count} 个待处理订单', lastActive: '{time} 活跃', noRuntimeData: '暂无运行记录'
  },
  research: {
    title: 'AI投研', subtitle: '像和研究员对话一样分析标的', history: '历史', newChat: '新对话', selectSymbol: '选择标的', assistantName: 'QuantDinger 研究助手',
    welcome: '告诉我你想研究的标的和问题，我会给出结论、证据和风险。', sampleUser: '分析一下 BTC/USDT 最近的趋势，现在适合关注吗？',
    sampleAnswer: '短期仍处于上升结构，但价格接近前高，追涨的风险高于等待回踩。可以重点观察成交量和 4 小时级别支撑。', conclusion: '结论', evidence: '关键证据',
    evidenceOne: '4 小时均线保持多头排列', evidenceTwo: '上涨时成交量温和放大', evidenceThree: '前高附近存在明显抛压', source: '数据截至 {time} · 4小时周期',
    fullReport: '查看完整报告', openIndicator: '打开指标图表', suggestions: '你还可以问', promptOne: '关键支撑位在哪里？', promptTwo: '有哪些风险需要注意？', promptThree: '和 ETH 对比一下',
    placeholder: '输入你想研究的问题…', send: '发送', sending: '分析中…', failed: '分析失败，请稍后重试', emptyHistory: '还没有历史对话', disclaimer: 'AI 结论仅供研究参考，不构成投资建议。', subtitleShort: '问市场，也问证据', sampleUserShort: '帮我分析一下 BTC 现在适不适合关注？', sampleAnswerShort: '短期方向不明确，追涨风险较高，可以等待趋势确认。', judgement: '当前判断：高波动震荡', trend: '趋势', neutral: '中性', trendDesc: '短期方向不明确，区间波动为主。', risk: '风险', high: '偏高', riskDesc: '市场波动较大，追涨风险较高。', sentiment: '情绪', cautious: '谨慎', sentimentDesc: '市场情绪偏谨慎，观望情绪较浓。', sourceFull: '依据：价格、成交量、市场情绪、宏观日历 · 更新于 {time} {date}', continueHint: '你还可以继续问：关键支撑位、近期新闻、适合什么策略。', promptPrice: '关键价位', promptNews: '分析新闻', promptStrategy: '适合什么策略', placeholderShort: '继续问 BTC…'
  },
  indicator: { previewName: 'EMA 趋势', signalSummary: '指标信号', bullish: '偏多', confidence: '信号强度', previewOrder: '预览订单', mainChart: '主图', subChart: '副图', signalText: 'EMA20 位于 EMA60 上方，趋势偏强', aiExplain: 'AI 解释', all: '全部', previewBuy: '预览买入订单', previewAccount: 'Binance 主账户', m1: '1分', m5: '5分', m15: '15分', h1: '1时', h4: '4时', day: '日线' },
  profile: {
    title: '我的', subtitle: '账户、交易连接与应用设置', credits: '积分余额', purchases: '已购策略', broker: '交易账户', brokerDesc: '连接交易所或券商，用于策略和闪电交易', accountSecurity: '账户安全', notification: '通知设置', language: '语言', appearance: '外观', dark: '深色', light: '浅色', about: '关于 QuantDinger', logout: '退出登录', vip: '会员', normal: '普通用户', edit: '编辑资料', invite: '邀请好友', previewName: '林先生', points: '积分', boughtStrategies: '已购策略', boughtIndicators: '已购指标', mainAccount: '主账户', connected: '连接正常', notConnected: '未连接', synced: '最近同步 2 分钟前', assetsServices: '资产与服务', myPurchases: '我的购买', pointsMember: '积分与会员', rechargeOrders: '充值与订单', security: '安全', mfa: 'MFA 双重验证', enabled: '已开启', loginLog: '登录记录', preferenceSupport: '偏好与支持', languageTheme: '语言与主题', helpFeedback: '帮助与反馈'
  }
}

const enUS = {
  nav: { strategy: 'Home', live: 'Run', research: 'AI Research', indicator: 'Indicators', profile: 'Me' },
  common: { notifications: 'Notifications', createStrategy: 'Run strategy', retry: 'Reload', loading: 'Loading', more: 'View more', today: 'Today', cumulative: 'Total', account: 'Account', settings: 'Settings' },
  strategy: {
    title: 'Strategies', subtitle: 'Choose a strategy and invest more simply', featured: 'Featured', mine: 'My strategies', preferenceTitle: 'What matters most?', stable: 'Steadier', stableDesc: 'Control drawdown', balanced: 'Balanced', balancedDesc: 'Growth and risk', active: 'More active', activeDesc: 'Higher return', recommended: 'For you', spot: 'Spot', riskLow: 'Low risk', riskMedium: 'Medium risk', riskHigh: 'High risk', return: 'Historical return', yearReturn: '1Y return', drawdown: 'Max drawdown', users: '{count} users', simulate: 'Try simulation', details: 'Details', viewAll: 'View all', cost: 'Cost', free: 'Free', moreTitle: 'More for beginners', emptyTitle: 'No matching strategies', emptyDesc: 'Try another preference or check again later.', mineEmptyTitle: 'No strategies yet', mineEmptyDesc: 'Start from a template without writing code.', mineAction: 'Browse strategies', runNow: 'Connect live', statusRunning: 'Running', statusStopped: 'Stopped', statusError: 'Needs attention', fallbackName: 'BTC Trend Follower', fallbackDesc: 'Built for trends after volatile ranges', secondName: 'ETH Low-Frequency Grid', secondDesc: 'Buys low and sells high in ranges', thirdName: 'Multi-coin Rotation', thirdDesc: 'Diversifies across major coins', marketTitle: 'Strategy Market', search: 'Search strategies', welcomeEyebrow: 'Open-source AI Trading OS', welcomeTitle: 'Welcome to QuantDinger', welcomeSubtitle: 'Discover data-backed strategies and follow the markets that matter to you.', riskPreference: 'Choose your risk preference', stableRanking: 'Ranked by lowest maximum drawdown', balancedRanking: 'Ranked by return-to-drawdown ratio and market interest', activeRanking: 'Ranked by historical return and market interest', popularRanking: 'Popular strategy ranking', viewMore: 'View more', statisticsPeriod: 'Period', backtestSamples: 'Backtest samples', returnDrawdownRatio: 'Return / drawdown', winRate: 'Win rate', sharpeRatio: 'Sharpe ratio', profitLossRatio: 'Payoff ratio', updated: 'Updated', performanceNotice: 'Past performance does not guarantee future returns', watchlistTitle: 'My watchlist', watchlistSubtitle: 'Latest quotes for the assets you follow', manageWatchlist: 'Manage', watchlistAsset: 'Asset', watchlistPrice: 'Last price', watchlistChange: '24h change', watchlistEmpty: 'Your watchlist is empty', watchlistEmptyDesc: 'Add assets you follow to see their latest moves here.', addWatchlist: 'Add assets', dataRiskTitle: 'Data & risk controls', unifiedBacktest: 'Consistent backtests', unifiedBacktestDesc: 'Comparable results', riskComplete: 'Complete risk metrics', riskCompleteDesc: 'Return and drawdown', tradeConfirm: 'Confirm before live', tradeConfirmDesc: 'Review account and inputs', myRuntime: 'My runs', runningCount: 'running', attentionCount: 'to review', unnamed: 'Unnamed strategy', marketUnknown: 'Market details pending'
  },
  live: { title: 'Strategy runs', subtitle: 'Monitor strategy status, P&L, and runtime health.', console: 'Run center', attention: '{count} issue needs attention', attentionDesc: 'A strategy or account has an issue. Review it soon.', attentionShort: 'ETH grid account balance is low', view: 'Review now', todayPnl: "Today's P&L", totalPnl: 'Net P&L', running: 'Running', strategyUnit: 'strategies', drawdown: 'Drawdown', balanceLow: 'Available balance is below the safety line', handle: 'Handle', long: 'Long', readyCount: '{count} ready to start', total: 'All', positions: 'Positions', sectionRunning: 'Running', sectionAttention: 'Attention', sectionStopped: 'Stopped', noRunning: 'No running strategies', noRunningDesc: 'Choose a strategy and configure how it should run.', chooseStrategy: 'Choose strategy', updated: 'Updated just now', accountIssue: 'Reconnect the trading account', viewDetails: 'View details', profit: 'P&L', capital: 'Strategy capital', status: 'Status', start: 'Start', pause: 'Pause', systemHealthy: 'Runtime data is current', systemDegraded: 'Some data could not be loaded', strategyCount: '{count} strategies', requiresReview: 'Review', allClear: 'All clear', modeFilter: 'Execution mode', statusFilter: 'Runtime status', searchPlaceholder: 'Search strategy, symbol, or exchange', clearSearch: 'Clear search', noMatches: 'No matching strategies', updatedAt: 'Updated {time}', health_degraded: 'Degraded', health_stale: 'Delayed', health_offline: 'Offline', health_attention: 'Attention', spotMarket: 'Spot', swapMarket: 'Perpetual', strategyRuntime: 'Strategy', pendingOrders: '{count} pending orders', lastActive: 'Active {time}', noRuntimeData: 'No runtime record' },
  research: { title: 'AI Research', subtitle: 'Research assets through conversation', subtitleShort: 'Ask the market. Ask for evidence.', history: 'History', newChat: 'New chat', selectSymbol: 'Select symbol', assistantName: 'QuantDinger Research', welcome: 'Tell me the asset and question. I will return a conclusion, evidence, and risks.', sampleUser: 'Analyze the recent BTC/USDT trend. Is it worth watching now?', sampleUserShort: 'Is BTC worth watching now?', sampleAnswer: 'The short-term structure remains constructive, but price is close to prior resistance. Waiting for a pullback offers a better risk profile than chasing.', sampleAnswerShort: 'Short-term direction is unclear and chasing carries elevated risk. Wait for confirmation.', judgement: 'Current view: volatile range', trend: 'Trend', neutral: 'Neutral', trendDesc: 'Direction is unclear and price is range-bound.', risk: 'Risk', high: 'High', riskDesc: 'Volatility is elevated and chasing is risky.', sentiment: 'Sentiment', cautious: 'Cautious', sentimentDesc: 'Market participants remain cautious.', sourceFull: 'Based on price, volume, sentiment, and macro calendar · {time} {date}', continueHint: 'Continue with support levels, recent news, or suitable strategies.', promptPrice: 'Key levels', promptNews: 'Analyze news', promptStrategy: 'Suitable strategy', placeholderShort: 'Continue asking about BTC…', conclusion: 'Conclusion', evidence: 'Key evidence', evidenceOne: '4-hour averages remain positively aligned', evidenceTwo: 'Volume expands moderately on advances', evidenceThree: 'Prior highs still show visible selling pressure', source: 'Data as of {time} · 4H', fullReport: 'Full report', openIndicator: 'Open indicator chart', suggestions: 'Try asking', promptOne: 'Where is key support?', promptTwo: 'What risks matter most?', promptThree: 'Compare it with ETH', placeholder: 'Ask a research question…', send: 'Send', sending: 'Analyzing…', failed: 'Analysis failed. Try again.', emptyHistory: 'No previous chats', disclaimer: 'AI research is for reference only and is not investment advice.' },
  indicator: { previewName: 'EMA Trend', signalSummary: 'Indicator signal', bullish: 'Bullish', confidence: 'Signal strength', previewOrder: 'Preview order', mainChart: 'Main', subChart: 'Sub', signalText: 'EMA20 is above EMA60. Trend is firm.', aiExplain: 'AI insight', all: 'All', previewBuy: 'Preview buy order', previewAccount: 'Binance Main', m1: '1m', m5: '5m', m15: '15m', h1: '1h', h4: '4h', day: '1D' },
  profile: { title: 'Me', subtitle: 'Accounts, trading connections, and settings', credits: 'Credits', purchases: 'Purchased', broker: 'Trading account', brokerDesc: 'Connect an exchange or broker for strategies and quick trade', accountSecurity: 'Account security', notification: 'Notifications', language: 'Language', appearance: 'Appearance', dark: 'Dark', light: 'Light', about: 'About QuantDinger', logout: 'Sign out', vip: 'Member', normal: 'Standard', edit: 'Edit profile', invite: 'Invite friends', previewName: 'Mr. Lin', points: 'Points', boughtStrategies: 'Strategies', boughtIndicators: 'Indicators', mainAccount: 'Main account', connected: 'Connected', notConnected: 'Not connected', synced: 'Synced 2 minutes ago', assetsServices: 'Assets & services', myPurchases: 'My purchases', pointsMember: 'Points & membership', rechargeOrders: 'Top-up & orders', security: 'Security', mfa: 'MFA', enabled: 'Enabled', loginLog: 'Login history', preferenceSupport: 'Preferences & support', languageTheme: 'Language & theme', helpFeedback: 'Help & feedback' }
}

const zhTW = JSON.parse(JSON.stringify(zhCN))
Object.assign(zhTW.nav, { strategy: '首頁', live: '運行', research: 'AI投研', indicator: '指標', profile: '我的' })
Object.assign(zhTW.common, { createStrategy: '運行策略' })
Object.assign(zhTW.strategy, { subtitle: '選一個適合你的策略，連接帳戶後即可運行', featured: '精選', mine: '我的策略', simulate: '先模擬體驗', details: '查看詳情', runNow: '連接實盤', marketTitle: '策略市場', search: '搜尋策略', riskPreference: '風險取向', stableRanking: '按最大回撤由低至高排序', balancedRanking: '按收益回撤比與市場熱度綜合排序', activeRanking: '按歷史收益與市場熱度綜合排序', popularRanking: '熱門策略排名', viewMore: '查看更多', statisticsPeriod: '統計週期', backtestSamples: '回測樣本', winRate: '勝率', updated: '更新於', performanceNotice: '歷史表現不代表未來收益', dataRiskTitle: '資料與風控', unifiedBacktest: '統一回測口徑', unifiedBacktestDesc: '便於橫向比較', riskComplete: '風險指標完整', riskCompleteDesc: '收益與回撤同看', tradeConfirm: '實盤前二次確認', tradeConfirmDesc: '核對帳戶與參數', myRuntime: '我的運行', runningCount: '運行中', attentionCount: '待處理', unnamed: '未命名策略', marketUnknown: '市場資料待補充' })
Object.assign(zhTW.strategy, { welcomeEyebrow: '開源AI Trading OS', riskLow: '低風險', riskMedium: '中風險', riskHigh: '高風險', returnDrawdownRatio: '收益回撤比', sharpeRatio: '夏普比率', profitLossRatio: '盈虧比', welcomeTitle: '歡迎來到 QuantDinger', welcomeSubtitle: '探索經數據驗證的策略，關注你在意的市場。', riskPreference: '選擇適合你的風險偏好', watchlistTitle: '我的自選', watchlistSubtitle: '關注標的的最新行情', manageWatchlist: '管理自選', watchlistAsset: '標的', watchlistPrice: '最新價', watchlistChange: '24 小時漲跌', watchlistEmpty: '還沒有自選標的', watchlistEmptyDesc: '加入常看的標的，隨時掌握行情變化。', addWatchlist: '加入自選' })
Object.assign(zhTW.live, { title: '策略運行', subtitle: '統一查看策略狀態、盈虧和運行健康。', console: '運行中心', sectionRunning: '正在運行', sectionAttention: '需要處理', sectionStopped: '已停止', systemHealthy: '運行資料正常', systemDegraded: '部分資料載入失敗', strategyCount: '{count} 個策略', requiresReview: '待檢查', allClear: '狀態正常', modeFilter: '執行模式', statusFilter: '運行狀態', searchPlaceholder: '搜尋策略、標的或交易所', clearSearch: '清除搜尋', noMatches: '沒有符合條件的策略', updatedAt: '{time} 更新', health_degraded: '運行異常', health_stale: '資料延遲', health_offline: '已離線', health_attention: '需處理', spotMarket: '現貨', swapMarket: '永續', strategyRuntime: '策略運行', pendingOrders: '{count} 個待處理訂單', lastActive: '{time} 活躍', noRuntimeData: '暫無運行記錄' })
Object.assign(zhTW.profile, { broker: '交易帳戶', brokerDesc: '連接交易所或券商，用於策略和閃電交易', language: '語言', appearance: '外觀', dark: '深色', light: '淺色' })

const jaJP = JSON.parse(JSON.stringify(enUS))
Object.assign(jaJP.nav, { strategy: 'ホーム', live: '運用', research: 'AIリサーチ', indicator: '指標', profile: 'マイページ' })
Object.assign(jaJP.common, { notifications: '通知', createStrategy: '戦略を運用', retry: '再読み込み', loading: '読み込み中', more: 'もっと見る', today: '本日', cumulative: '累計', account: '口座', settings: '設定' })
Object.assign(jaJP.strategy, { title: '戦略', subtitle: '戦略を選び、口座を接続して運用を開始', featured: 'おすすめ', mine: 'マイ戦略', stable: '安定重視', stableDesc: 'ドローダウンを抑制', balanced: 'バランス', balancedDesc: '収益とリスク', active: '積極型', activeDesc: '高い収益を重視', recommended: '初心者におすすめ', spot: '現物', riskLow: '低リスク', riskMedium: '中リスク', riskHigh: '高リスク', return: '過去の収益率', drawdown: '最大ドローダウン', users: '{count}人が利用中', simulate: 'シミュレーション', details: '詳細を見る', moreTitle: '初心者向け戦略', emptyTitle: '該当する戦略がありません', emptyDesc: '条件を変更してもう一度お試しください。', mineEmptyTitle: '戦略がありません', mineEmptyDesc: 'コード不要のテンプレートから始められます。', mineAction: '戦略を探す', runNow: '実運用に接続', statusRunning: '運用中', statusStopped: '停止中', statusError: '確認が必要', fallbackName: 'BTCトレンドフォロー', fallbackDesc: '中期トレンドに沿って売買し、ポジションとドローダウンを自動管理します。', secondName: 'ETH移動平均プラン', secondDesc: 'トレンドフィルターで分割エントリーし、価格変動を抑えます。', thirdName: '主要通貨グリッド', thirdDesc: '設定レンジ内で自動的に安く買い、高く売ります。', marketTitle: '戦略市場', search: '戦略を検索', riskPreference: 'リスク志向', stableRanking: '最大ドローダウンの低い順', balancedRanking: 'リターン対ドローダウン比と市場人気で総合順位', activeRanking: '過去の収益率と市場人気で総合順位', popularRanking: '人気戦略ランキング', viewMore: 'もっと見る', statisticsPeriod: '集計期間', backtestSamples: 'バックテスト数', winRate: '勝率', updated: '更新日', performanceNotice: '過去の実績は将来の収益を保証しません', dataRiskTitle: 'データとリスク管理', unifiedBacktest: '統一テスト基準', unifiedBacktestDesc: '比較しやすい結果', riskComplete: 'リスク指標を表示', riskCompleteDesc: '収益と下落率', tradeConfirm: '実運用前に確認', tradeConfirmDesc: '口座と条件を確認', myRuntime: '運用中の戦略', runningCount: '運用中', attentionCount: '要確認', unnamed: '名称未設定', marketUnknown: '市場情報は準備中' })
Object.assign(jaJP.strategy, { welcomeEyebrow: 'オープンソース AI Trading OS', returnDrawdownRatio: 'リターン / ドローダウン', sharpeRatio: 'シャープレシオ', profitLossRatio: 'ペイオフレシオ', welcomeTitle: 'QuantDingerへようこそ', welcomeSubtitle: 'データに基づく戦略を見つけ、注目する市場を追跡します。', riskPreference: '自分に合うリスク選好を選択', watchlistTitle: 'ウォッチリスト', watchlistSubtitle: 'フォロー中の銘柄の最新価格', manageWatchlist: '管理', watchlistAsset: '銘柄', watchlistPrice: '現在値', watchlistChange: '24時間変動', watchlistEmpty: 'ウォッチリストは空です', watchlistEmptyDesc: 'よく見る銘柄を追加すると、ここで値動きを確認できます。', addWatchlist: '銘柄を追加' })
Object.assign(jaJP.live, { title: '実運用', subtitle: '戦略の状態、損益、稼働状況をまとめて確認', console: '運用コンソール', attention: '{count}件の確認が必要', attentionDesc: '戦略または口座に問題があります。早めに確認してください。', view: '確認する', todayPnl: '本日の損益', totalPnl: '累計損益', running: '運用中', total: 'すべて', positions: 'ポジション', sectionRunning: '運用中', sectionAttention: '要確認', sectionStopped: '停止中', noRunning: '運用中の戦略はありません', noRunningDesc: '戦略を選び、取引口座を接続してください。', chooseStrategy: '戦略を選ぶ', updated: 'たった今更新', accountIssue: '取引口座を再接続してください', viewDetails: '運用詳細', profit: '含み損益', capital: '戦略資金', status: '状態', start: '開始', pause: '停止', systemHealthy: '稼働データは正常です', systemDegraded: '一部のデータを取得できません', strategyCount: '{count}件', requiresReview: '確認待ち', allClear: '正常', modeFilter: '実行モード', statusFilter: '稼働状態', searchPlaceholder: '戦略・銘柄・取引所を検索', clearSearch: '検索を消去', noMatches: '該当する戦略がありません', updatedAt: '{time} 更新', health_degraded: '異常', health_stale: '遅延', health_offline: 'オフライン', health_attention: '要確認', spotMarket: '現物', swapMarket: '無期限', strategyRuntime: '戦略運用', pendingOrders: '保留注文 {count}件', lastActive: '{time} 稼働', noRuntimeData: '稼働記録なし' })
Object.assign(jaJP.research, { title: 'AIリサーチ', subtitle: '会話形式で銘柄を分析', history: '履歴', newChat: '新しい会話', selectSymbol: '銘柄を選択', assistantName: 'QuantDinger リサーチ', welcome: '調べたい銘柄と質問を入力してください。結論、根拠、リスクを整理します。', sampleUser: 'BTC/USDTの最近のトレンドを分析してください。', sampleAnswer: '短期の上昇構造は維持していますが、直近高値に近く、追随買いより押し目を待つ方がリスクを抑えられます。', conclusion: '結論', evidence: '主な根拠', evidenceOne: '4時間足の移動平均は上向き', evidenceTwo: '上昇局面で出来高が緩やかに増加', evidenceThree: '直近高値付近に売り圧力', source: '{time}時点 · 4時間足', fullReport: '完全なレポート', openIndicator: '指標チャートを開く', suggestions: '次の質問', promptOne: '重要な支持線は？', promptTwo: '注意すべきリスクは？', promptThree: 'ETHと比較して', placeholder: '調べたいことを入力…', send: '送信', sending: '分析中…', failed: '分析できませんでした。再試行してください。', emptyHistory: '履歴はありません', disclaimer: 'AI分析は参考情報であり、投資助言ではありません。' })
Object.assign(jaJP.indicator, { previewName: 'EMAトレンド', signalSummary: '指標シグナル', bullish: '強気', confidence: 'シグナル強度', previewOrder: '注文確認' })
Object.assign(jaJP.profile, { title: 'マイページ', subtitle: '口座・取引接続・アプリ設定', credits: 'クレジット', purchases: '購入済み', broker: '取引口座', brokerDesc: '取引所またはブローカーを接続して戦略とクイック注文に使用', accountSecurity: 'アカウントとセキュリティ', notification: '通知設定', language: '言語', appearance: '表示', dark: 'ダーク', light: 'ライト', about: 'QuantDingerについて', logout: 'ログアウト', vip: '会員', normal: '一般ユーザー', edit: 'プロフィール編集', invite: '友達を招待' })
Object.assign(jaJP.strategy, { preferenceTitle: '重視するポイント', yearReturn: '1年リターン', viewAll: 'すべて表示', cost: '価格', free: '無料' })
Object.assign(jaJP.live, { attentionShort: 'ETHグリッド口座の残高が不足しています', strategyUnit: '件', drawdown: 'ドローダウン', balanceLow: '利用可能残高が安全基準を下回っています', handle: '対応', long: 'ロング', readyCount: '{count}件が開始可能' })
Object.assign(jaJP.research, { subtitleShort: '市場に問い、根拠を確認。', sampleUserShort: '今、BTCに注目すべきですか？', sampleAnswerShort: '短期方向は不明確で、追随には高いリスクがあります。確認を待ちましょう。', judgement: '現在の見方：変動の大きいレンジ', trend: 'トレンド', neutral: '中立', trendDesc: '方向は不明確で、価格はレンジ内です。', risk: 'リスク', high: '高い', riskDesc: 'ボラティリティが高く、追随は危険です。', sentiment: 'センチメント', cautious: '慎重', sentimentDesc: '市場参加者は慎重な姿勢を維持しています。', sourceFull: '価格、出来高、センチメント、経済指標カレンダーに基づく · {time} {date}', continueHint: '支持線、最近のニュース、適した戦略について続けて質問できます。', promptPrice: '重要な価格帯', promptNews: 'ニュースを分析', promptStrategy: '適した戦略', placeholderShort: 'BTCについて続けて質問…' })
Object.assign(jaJP.indicator, { mainChart: 'メイン', subChart: 'サブ', signalText: 'EMA20がEMA60を上回り、トレンドは堅調です。', aiExplain: 'AI分析', all: 'すべて', previewBuy: '買い注文を確認', previewAccount: 'Binance メイン' })
Object.assign(jaJP.profile, { previewName: '林さん', points: 'ポイント', boughtStrategies: '戦略', boughtIndicators: '指標', mainAccount: 'メイン口座', connected: '接続済み', notConnected: '未接続', synced: '2分前に同期', assetsServices: '資産とサービス', myPurchases: '購入済み', pointsMember: 'ポイントと会員', rechargeOrders: 'チャージと注文', security: 'セキュリティ', mfa: '多要素認証', enabled: '有効', loginLog: 'ログイン履歴', preferenceSupport: '設定とサポート', languageTheme: '言語とテーマ', helpFeedback: 'ヘルプとフィードバック' })

const koKR = JSON.parse(JSON.stringify(enUS))
Object.assign(koKR.nav, { strategy: '홈', live: '실행', research: 'AI 리서치', indicator: '지표', profile: '내 정보' })
Object.assign(koKR.common, { notifications: '알림', createStrategy: '전략 실행', retry: '다시 불러오기', loading: '불러오는 중', more: '더 보기', today: '오늘', cumulative: '누적', account: '계정', settings: '설정' })
Object.assign(koKR.strategy, { title: '전략', subtitle: '전략을 선택하고 계좌를 연결해 실행하세요', featured: '추천', mine: '내 전략', stable: '안정형', stableDesc: '낙폭 관리', balanced: '균형형', balancedDesc: '수익과 위험', active: '적극형', activeDesc: '높은 수익 추구', recommended: '초보자 추천', spot: '현물', riskLow: '낮은 위험', riskMedium: '중간 위험', riskHigh: '높은 위험', return: '과거 수익률', drawdown: '최대 낙폭', users: '{count}명 사용 중', simulate: '모의 실행', details: '상세 보기', moreTitle: '초보자용 전략', emptyTitle: '조건에 맞는 전략이 없습니다', emptyDesc: '다른 성향을 선택하거나 나중에 다시 확인하세요.', mineEmptyTitle: '내 전략이 없습니다', mineEmptyDesc: '코드 없이 템플릿으로 시작할 수 있습니다.', mineAction: '전략 선택', runNow: '실거래 연결', statusRunning: '실행 중', statusStopped: '중지됨', statusError: '확인 필요', fallbackName: 'BTC 추세 추종', fallbackDesc: '중기 추세를 따라 거래하고 포지션과 낙폭을 자동 관리합니다.', secondName: 'ETH 이동평균 플랜', secondDesc: '추세 필터로 분할 진입해 변동성을 줄입니다.', thirdName: '주요 코인 그리드', thirdDesc: '설정 구간에서 자동으로 저가 매수와 고가 매도를 실행합니다.', marketTitle: '전략 시장', search: '전략 검색', riskPreference: '위험 성향', stableRanking: '최대 낙폭이 낮은 순서', balancedRanking: '수익 대비 낙폭과 시장 관심도를 종합한 순서', activeRanking: '과거 수익률과 시장 관심도를 종합한 순서', popularRanking: '인기 전략 순위', viewMore: '더 보기', statisticsPeriod: '통계 기간', backtestSamples: '백테스트 표본', winRate: '승률', updated: '업데이트', performanceNotice: '과거 성과가 미래 수익을 보장하지 않습니다', dataRiskTitle: '데이터 및 위험 관리', unifiedBacktest: '동일한 테스트 기준', unifiedBacktestDesc: '비교 가능한 결과', riskComplete: '위험 지표 공개', riskCompleteDesc: '수익과 낙폭 확인', tradeConfirm: '실행 전 재확인', tradeConfirmDesc: '계정과 조건 확인', myRuntime: '내 실행', runningCount: '실행 중', attentionCount: '확인 필요', unnamed: '이름 없는 전략', marketUnknown: '시장 정보 준비 중' })
Object.assign(koKR.strategy, { welcomeEyebrow: '오픈소스 AI Trading OS', returnDrawdownRatio: '수익 / 낙폭', sharpeRatio: '샤프 비율', profitLossRatio: '손익비', welcomeTitle: 'QuantDinger에 오신 것을 환영합니다', welcomeSubtitle: '데이터로 검증된 전략을 찾고 관심 시장을 확인하세요.', riskPreference: '나에게 맞는 위험 성향 선택', watchlistTitle: '내 관심 종목', watchlistSubtitle: '관심 자산의 최신 시세', manageWatchlist: '관리', watchlistAsset: '자산', watchlistPrice: '현재가', watchlistChange: '24시간 등락', watchlistEmpty: '관심 종목이 없습니다', watchlistEmptyDesc: '자주 보는 자산을 추가해 시세를 확인하세요.', addWatchlist: '종목 추가' })
Object.assign(koKR.live, { title: '실거래 운영', subtitle: '전략 상태, 손익, 실행 상태를 한눈에 확인하세요.', console: '운영 콘솔', attention: '{count}건 확인 필요', attentionDesc: '전략 또는 계정 상태에 문제가 있습니다.', view: '지금 확인', todayPnl: '오늘 손익', totalPnl: '누적 손익', running: '실행 중', total: '전체', positions: '포지션', sectionRunning: '실행 중', sectionAttention: '확인 필요', sectionStopped: '중지됨', noRunning: '실행 중인 전략이 없습니다', noRunningDesc: '전략을 선택하고 거래 계정을 연결하세요.', chooseStrategy: '전략 선택', updated: '방금 업데이트', accountIssue: '거래 계정을 다시 연결하세요', viewDetails: '운영 상세', profit: '평가 손익', capital: '전략 자금', status: '상태', start: '시작', pause: '중지', systemHealthy: '실행 데이터 정상', systemDegraded: '일부 데이터를 불러오지 못했습니다', strategyCount: '{count}개 전략', requiresReview: '검토 필요', allClear: '정상', modeFilter: '실행 모드', statusFilter: '실행 상태', searchPlaceholder: '전략, 종목 또는 거래소 검색', clearSearch: '검색 지우기', noMatches: '일치하는 전략이 없습니다', updatedAt: '{time} 업데이트', health_degraded: '실행 이상', health_stale: '데이터 지연', health_offline: '오프라인', health_attention: '확인 필요', spotMarket: '현물', swapMarket: '무기한', strategyRuntime: '전략 실행', pendingOrders: '대기 주문 {count}건', lastActive: '{time} 활성', noRuntimeData: '실행 기록 없음' })
Object.assign(koKR.research, { title: 'AI 리서치', subtitle: '대화로 종목을 분석하세요', history: '기록', newChat: '새 대화', selectSymbol: '종목 선택', assistantName: 'QuantDinger 리서치', welcome: '분석할 종목과 질문을 알려주세요. 결론, 근거, 위험을 정리합니다.', sampleUser: 'BTC/USDT의 최근 추세를 분석해 주세요.', sampleAnswer: '단기 상승 구조는 유지되지만 이전 고점에 가까워 추격 매수보다 조정을 기다리는 편이 위험이 낮습니다.', conclusion: '결론', evidence: '핵심 근거', evidenceOne: '4시간 이동평균이 상승 정렬을 유지', evidenceTwo: '상승 구간에서 거래량이 완만하게 증가', evidenceThree: '이전 고점 부근에 매도 압력 존재', source: '{time} 기준 · 4시간', fullReport: '전체 보고서', openIndicator: '지표 차트 열기', suggestions: '이어서 질문', promptOne: '주요 지지선은?', promptTwo: '주의할 위험은?', promptThree: 'ETH와 비교해 줘', placeholder: '궁금한 내용을 입력하세요…', send: '전송', sending: '분석 중…', failed: '분석에 실패했습니다. 다시 시도하세요.', emptyHistory: '대화 기록이 없습니다', disclaimer: 'AI 분석은 참고용이며 투자 조언이 아닙니다.' })
Object.assign(koKR.indicator, { previewName: 'EMA 추세', signalSummary: '지표 신호', bullish: '강세', confidence: '신호 강도', previewOrder: '주문 미리보기' })
Object.assign(koKR.profile, { title: '내 정보', subtitle: '계정, 거래 연결 및 앱 설정', credits: '크레딧', purchases: '구매한 전략', broker: '거래 계정', brokerDesc: '거래소 또는 브로커를 연결해 전략과 빠른 거래에 사용', accountSecurity: '계정 및 보안', notification: '알림 설정', language: '언어', appearance: '화면', dark: '다크', light: '라이트', about: 'QuantDinger 정보', logout: '로그아웃', vip: '회원', normal: '일반 사용자', edit: '프로필 수정', invite: '친구 초대' })
Object.assign(koKR.strategy, { preferenceTitle: '가장 중요한 기준', yearReturn: '1년 수익률', viewAll: '전체 보기', cost: '가격', free: '무료' })
Object.assign(koKR.live, { attentionShort: 'ETH 그리드 계정 잔고가 부족합니다', strategyUnit: '개 전략', drawdown: '낙폭', balanceLow: '사용 가능 잔고가 안전 기준보다 낮습니다', handle: '처리', long: '롱', readyCount: '{count}개 시작 가능' })
Object.assign(koKR.research, { subtitleShort: '시장에 묻고 근거를 확인하세요.', sampleUserShort: '지금 BTC를 주목할 만한가요?', sampleAnswerShort: '단기 방향이 불분명하고 추격 진입 위험이 높습니다. 확인을 기다리세요.', judgement: '현재 판단: 변동성 높은 횡보', trend: '추세', neutral: '중립', trendDesc: '방향이 불분명하며 가격이 구간 내에서 움직입니다.', risk: '위험', high: '높음', riskDesc: '변동성이 높아 추격 진입은 위험합니다.', sentiment: '심리', cautious: '신중', sentimentDesc: '시장 참여자들은 신중한 태도를 유지하고 있습니다.', sourceFull: '가격, 거래량, 시장 심리 및 경제 일정 기준 · {time} {date}', continueHint: '지지선, 최근 뉴스 또는 적합한 전략을 계속 질문할 수 있습니다.', promptPrice: '주요 가격대', promptNews: '뉴스 분석', promptStrategy: '적합한 전략', placeholderShort: 'BTC에 대해 계속 질문…' })
Object.assign(koKR.indicator, { mainChart: '메인', subChart: '보조', signalText: 'EMA20이 EMA60 위에 있어 추세가 견조합니다.', aiExplain: 'AI 분석', all: '전체', previewBuy: '매수 주문 미리보기', previewAccount: 'Binance 메인' })
Object.assign(koKR.profile, { previewName: '린 님', points: '포인트', boughtStrategies: '전략', boughtIndicators: '지표', mainAccount: '메인 계정', connected: '연결됨', notConnected: '연결 안 됨', synced: '2분 전 동기화', assetsServices: '자산 및 서비스', myPurchases: '구매 내역', pointsMember: '포인트 및 멤버십', rechargeOrders: '충전 및 주문', security: '보안', mfa: '다단계 인증', enabled: '사용 중', loginLog: '로그인 기록', preferenceSupport: '환경설정 및 지원', languageTheme: '언어 및 테마', helpFeedback: '도움말 및 피드백' })

export default { 'zh-CN': zhCN, 'zh-TW': zhTW, 'en-US': enUS, 'ja-JP': jaJP, 'ko-KR': koKR }
