import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path) => readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8')

test('web and Docker API defaults stay deployable without a forced hosted API', () => {
  const config = read('src/config/index.js')
  const vite = read('vite.config.js')
  const nginx = read('deploy/nginx-mobile.conf')
  const dockerfile = read('Dockerfile')

  assert.match(config, /VITE_DEFAULT_SERVER_URL/)
  assert.match(config, /VITE_DEFAULT_SERVER_URL\)[\s\S]*\|\|[\s\S]*webOrigin/)
  assert.doesNotMatch(config, /api\.quantdinger\.com|OFFICIAL_SERVER_URL/)
  assert.match(config, /VITE_PUBLIC_WEB_BASE_URL[\s\S]*webOrigin/)
  assert.match(vite, /loadEnv\(mode, __dirname, ''\)/)
  assert.match(vite, /VITE_DEV_API_TARGET/)
  assert.match(vite, /'http:\/\/127\.0\.0\.1:5000'/)
  assert.match(nginx, /proxy_pass \$backend_upstream/)
  assert.match(dockerfile, /BACKEND_URL=http:\/\/backend:5000/)
  assert.equal(existsSync(new URL('../../.env.production', import.meta.url)), false)
})

test('legacy pages are retired while quick trade redirects into the signal chart', () => {
  const router = read('src/router/index.js')
  const app = read('src/App.vue')
  const main = read('src/main.js')

  assert.match(router, /path: '\/home',\s+redirect: '\/market'/)
  assert.match(router, /path: '\/quick-trade',[\s\S]*redirect: to => \(\{ path: '\/indicators\/chart', query: \{ \.\.\.to.query, trade: '1' \} \}\)/)
  assert.doesNotMatch(router, /views\/(?:home|quick-trade)/)
  assert.doesNotMatch(router, /showTabbar/)
  assert.doesNotMatch(app, /QuickTrade|name: 'Home'|path: '\/quick-trade'/)
  assert.doesNotMatch(main, /'\/quick-trade'|'\/home'/)
  assert.equal(existsSync(new URL('../../src/views/home/index.vue', import.meta.url)), false)
  assert.equal(existsSync(new URL('../../src/views/quick-trade/index.vue', import.meta.url)), false)
})

test('mobile source exposes safe chart trading without code generation', () => {
  const api = read('src/api/index.js')
  const stores = read('src/stores/index.js')
  const createStrategy = read('src/views/trading/CreateStrategy.vue')
  const analysis = read('src/views/ai-analysis/index.vue')

  assert.match(api, /quickTradeApi/)
  assert.match(api, /\/api\/quick-trade\/place-order/)
  assert.match(api, /\/api\/quick-trade\/close-position/)
  assert.doesNotMatch(api, /dashboardApi/)
  assert.doesNotMatch(api, /\/api\/strategies\/generate|script-sources\/create/)
  assert.match(stores, /useQuickTradeStore/)
  assert.doesNotMatch(createStrategy, /strategyApi\.generate|scriptSourceApi\.create|generateSourceFromPrompt/)
  assert.doesNotMatch(createStrategy, /<textarea|contenteditable|monaco|codemirror/i)
  assert.match(analysis, /<ProfessionalAnalysisReport/)
  assert.doesNotMatch(analysis, /chooseStrategy\(\)|generateStrategyFromResult|query: \{ prompt/)
})

test('AI action boundary blocks desktop-only workflows without blocking strategy usage', () => {
  const aiHub = read('src/views/ai-hub/index.vue') + read('src/locales/ai-chat.js')

  assert.match(aiHub, /unsupported_mobile_workflows: \['code_editing', 'backtest'\]/)
  assert.match(aiHub, /isUnsupportedMobileAction\(action\)/)
  assert.match(aiHub, /generate\[-_\]\?\(code\|strategy\)/)
  assert.doesNotMatch(aiHub, /\/backtest\|indicator\|script\|code\//)
  assert.match(aiHub, /name: 'StrategyDetail'/)
  assert.match(aiHub, /name: 'MarketIndicatorDetail'/)
  assert.match(aiHub, /agentUsageItems\(msg\)\.length/)
  assert.match(aiHub, /payload\.skills/)
  assert.match(aiHub, /payload\.tools/)
  assert.match(aiHub, /action\?\.type !== 'agent_usage'/)
})

test('live account and stop controls preserve explicit safety boundaries', () => {
  const api = read('src/api/index.js')
  const credentialForm = read('src/views/profile/CredentialForm.vue')
  const credentialList = read('src/views/profile/Credentials.vue')
  const strategyDetail = read('src/views/trading/StrategyDetail.vue')
  const liveOverview = read('src/views/v2/LiveOverview.vue')

  assert.match(api, /test: \(data\) => http\.post\('\/api\/credentials\/test'/)
  assert.match(api, /updateName: \(id, name\) => http\.put\('\/api\/credentials\/update-name'/)
  assert.match(api, /close_positions: Boolean\(closePositions\)/)
  assert.match(api, /getCommandStatus: \(id, commandId\)/)
  assert.match(api, /suppressErrorToast: true/)
  assert.match(credentialForm, /testConnection\(\)/)
  assert.match(credentialForm, /credentialsApi\.test\(this\.credentialPayload\(\)\)/)
  assert.match(credentialForm, /credentialsApi\.getEgressIp\(\)/)
  assert.ok(credentialForm.indexOf('account-card') < credentialForm.indexOf('egress-card'))
  assert.ok(credentialForm.indexOf('egress-card') < credentialForm.indexOf('key-card'))
  assert.match(credentialList, /credentialsApi\.updateName\(id, name\)/)
  assert.doesNotMatch(credentialList, /credentialsApi\.getEgressIp\(\)/)
  assert.doesNotMatch(credentialList, /credentialsApi\.get\(/)
  assert.match(strategyDetail, /@click="confirmStop\(false\)"/)
  assert.match(strategyDetail, /@click="confirmStop\(true\)"/)
  assert.match(strategyDetail, /strategyApi\.stop\(this\.strategyId, closePositions\)/)
  assert.match(strategyDetail, /waitForStrategyCommand/)
  assert.match(strategyDetail, /strategyApi\.getCommandStatus\(strategyId, commandId\)/)
  assert.match(strategyDetail, /hasRetainedLivePosition/)
  assert.match(strategyDetail, /@click="confirmCloseRetained"/)
  assert.match(strategyDetail, /this\.submitStop\(true\)/)
  assert.match(liveOverview, /strategyApi\.getList\(\)/)
  assert.match(liveOverview, /executionModeOf\(item\) === executionMode\.value/)
  assert.match(liveOverview, /Boolean\(item\?\.error_message\)/)
})

test('strategy detail uses the desktop operations data sources without automatic paid review generation', () => {
  const api = read('src/api/index.js')
  const strategyDetail = read('src/views/trading/StrategyDetail.vue')

  assert.match(api, /getTradeLedger:[\s\S]*\/api\/strategies\/trades/)
  assert.match(api, /cost_summary: payload\.cost_summary/)
  assert.match(api, /getEquityCurve:[\s\S]*\/api\/strategies\/equityCurve/)
  assert.match(api, /getPerformance:[\s\S]*\/api\/strategies\/performance/)
  assert.match(api, /getAiDecisions:[\s\S]*\/api\/strategies\/ai-decisions/)
  assert.match(api, /getReviewHistory:[\s\S]*\/api\/strategies\/review-report\/history/)
  assert.match(api, /generateReview:[\s\S]*\/api\/strategies\/review-report/)

  assert.match(strategyDetail, /strategyApi\.getTradeLedger\(this\.strategyId\)/)
  assert.match(strategyDetail, /strategyApi\.getPerformance\(this\.strategyId\)/)
  assert.match(strategyDetail, /strategyApi\.getEquityCurve\(this\.strategyId\)/)
  assert.match(strategyDetail, /strategyApi\.getAiDecisions\(this\.strategyId\)/)
  assert.match(strategyDetail, /showConfirmDialog[\s\S]*strategyApi\.generateReview/)
  const initialLoad = strategyDetail.match(/async load\(\)[\s\S]*?async loadOwnership/)?.[0] || ''
  assert.doesNotMatch(initialLoad, /generateReview/)
  assert.match(strategyDetail, /logFilterOptions/)
  assert.match(strategyDetail, /filteredLogs/)
  assert.match(strategyDetail, /\.equity-area\{fill:var\(--accent-soft\);stroke:none\}/)
  assert.doesNotMatch(strategyDetail, /var\(--primary\)/)
})

test('mobile navigation and visible Chinese copy describe strategy use, not coding or backtesting', () => {
  const app = read('src/App.vue')
  const styles = read('src/styles/index.css')
  const locale = read('src/locales/zh-CN.js')

  assert.match(app, /grid-template-columns: repeat\(5/)
  assert.match(app, /v2\.nav\.research/)
  assert.doesNotMatch(app, /tabs\.trade|key: 'trade'/)
  assert.match(app, /v2\.nav\.strategy/)
  assert.doesNotMatch(app, /shell-sidebar|sidebar\.open_navigation/)
  assert.doesNotMatch(styles, /van-tabbar/)
  assert.match(locale, /choose_strategy: '选择已有策略'/)
  assert.match(locale, /sync_code: '更新版本'/)
  assert.match(locale, /title: '策略配置'/)
  assert.doesNotMatch(locale, /go_backtest|generate_strategy/)
})

test('indicator chart embeds guarded quick trade without tasks or backtests', () => {
  const api = read('src/api/index.js')
  const router = read('src/router/index.js')
  const chart = read('src/views/indicator/Chart.vue')

  assert.match(router, /path: '\/indicators\/chart'/)
  assert.match(router, /path: '\/indicators\/monitor',\s+redirect: '\/indicators\/chart'/)
  assert.match(api, /previewChart:[\s\S]*\/api\/indicator\/chart-preview/)
  assert.doesNotMatch(api, /getSignalAlerts|createSignalAlert|\/api\/indicator\/signal-alerts/)
  const panel = read('src/components/ChartTradePanel.vue')
  assert.match(chart, /<MarketChart/)
  assert.match(chart, /<ChartTradePanel/)
  assert.match(panel, /chart_trade\.live_warning/)
  assert.doesNotMatch(chart, /strategyApi|orderApi|backtestApi/)
  assert.match(panel, /showConfirmDialog/)
  assert.match(read('src/utils/tradeOrder.js'), /source:\s*'indicator'/)
  assert.match(read('src/components/ChartTradePanel.vue'), /quickTradeApi\.placeOrder/)
  assert.doesNotMatch(chart, /<textarea|contenteditable|monaco|codemirror/i)
})

test('navigation removes universe, monitoring, and standalone choose-strategy entries', () => {
  const api = read('src/api/index.js')
  const router = read('src/router/index.js')
  const stores = read('src/stores/index.js')
  const app = read('src/App.vue')
  const aiHub = read('src/views/ai-hub/index.vue') + read('src/locales/ai-chat.js')

  assert.match(router, /path: '\/universes',\s+redirect: '\/ai'/)
  assert.doesNotMatch(api, /universeApi|\/api\/universes/)
  assert.doesNotMatch(stores, /useUniverseStore|selected_universe/)
  assert.doesNotMatch(aiHub, /universe_id|universe_code|useUniverseStore/)
  assert.doesNotMatch(app, /create-bot|indicator-monitor|universes|shell-sidebar/)
  assert.match(app, /key: 'strategy'[\s\S]*key: 'live'[\s\S]*key: 'research'[\s\S]*key: 'indicator'[\s\S]*key: 'profile'/)
  assert.doesNotMatch(app, /key: 'trade'/)
})

test('profile supports user-facing fields without exposing developer administration', () => {
  const api = read('src/api/index.js')
  const app = read('src/App.vue')
  const profile = read('src/views/v2/ProfileHub.vue') + read('src/views/profile/Account.vue') + read('src/views/profile/Language.vue')
  const marketDetail = read('src/views/market/Detail.vue')
  const purchases = read('src/views/market/MyPurchases.vue')
  const credits = read('src/views/profile/Credits.vue')

  assert.match(api, /updateProfile: \(data\) => http\.put\('\/api\/users\/profile\/update'/)
  assert.match(profile, /userApi\.updateProfile\(/)
  assert.match(profile, /nickname/)
  assert.match(profile, /avatar/)
  assert.match(profile, /timezone/)
  assert.match(profile, /\/profile\/language/)
  assert.match(profile, /useSettingsStore/)
  assert.match(profile, /setTheme/)
  assert.match(credits, /left-arrow/)
  assert.match(credits, /@click-left="goBack"/)
  assert.doesNotMatch(app, /agent[-_ ]?token|skill[-_ ]?(install|center)/i)
  assert.doesNotMatch(profile, /agent[-_ ]?token|skill[-_ ]?(install|center)/i)
  assert.match(marketDetail, /indicator\?\.local_copy_id/)
  assert.match(app, /--shell-tabbar-height: calc\(68px \+ var\(--safe-area-bottom\)\)/)
  assert.match(marketDetail, /bottom: var\(--shell-tabbar-height/)
  assert.match(purchases, /item\.local_copy_id/)
})

test('mobile safety states are visible before strategy mutations', () => {
  const strategyDetail = read('src/views/trading/StrategyDetail.vue')
  const liveOverview = read('src/views/v2/LiveOverview.vue')

  assert.match(strategyDetail, /hasUnmanagedPosition/)
  assert.match(strategyDetail, /stopped_with_positions/)
  assert.match(strategyDetail, /:disabled="hasOpenExposure \|\| !exposureReady"/)
  assert.match(strategyDetail, /delete_blocked_exposure/)
  assert.match(strategyDetail, /bottom: var\(--shell-tabbar-height/)
  assert.match(liveOverview, /function needsAttention\(item\)/)
  assert.match(liveOverview, /position_drift_blocked/)
  assert.match(liveOverview, /failed_orders/)
})

test('notifications retain individual records and structured details', () => {
  const notifications = read('src/views/profile/Notifications.vue')

  assert.match(notifications, /groupedNotifications\(\)/)
  assert.match(notifications, /notificationFields\(item\)/)
  assert.match(notifications, /categoryFilters\(\)/)
  assert.match(notifications, /notifications\.action_\$\{action\}/)
  assert.match(notifications, /notification-fields/)
  assert.match(notifications, /view_strategy/)
})

test('signal and live configuration expose only relevant fields', () => {
  const createStrategy = read('src/views/trading/CreateStrategy.vue')
  const router = read('src/router/index.js')

  assert.match(router, /path: '\/trading\/create',[\s\S]*component: \(\) => import\('@\/views\/trading\/CreateStrategy\.vue'\)/)
  assert.match(router, /path: '\/trading\/create\/configure'/)
  assert.match(router, /redirect: to => \(\{ path: '\/trading\/create', query: to\.query \}\s*\)/)
  assert.equal(existsSync(new URL('../../src/views/trading/CreateBot.vue', import.meta.url)), false)
  assert.match(createStrategy, /showSourcePicker/)
  assert.match(createStrategy, /source-picker-popup/)
  assert.match(createStrategy, /source-primary-action/)
  assert.match(createStrategy, /source_change_action/)
  assert.match(createStrategy, /scriptSourceApi\.getList\(\)/)
  assert.match(createStrategy, /v-if="sourceId && !contractError"/)
  assert.match(createStrategy, /v-if="form\.executionMode === 'live'"/)
  assert.doesNotMatch(createStrategy, /v-if="form\.executionMode === 'live'"\s+v-model\.number="form\.initialCapital"/)
  assert.match(createStrategy, /initialCapital: Number\(this\.form\.initialCapital\) \|\| 0/)
  assert.match(createStrategy, /initialCapital < 1 \|\| initialCapital > 1000000000/)
  assert.match(createStrategy, /hasEquityRisk/)
  assert.match(createStrategy, /metadata\.equity_risk/)
  assert.match(createStrategy, /equity_risk_hint/)
  assert.match(createStrategy, /van-checkbox-group v-model="notificationChannels"/)
  assert.match(createStrategy, /notificationChannelOptions/)
  assert.match(createStrategy, /activeNotificationChannels\.length/)
  assert.match(createStrategy, /profile\/notification-settings/)
  assert.match(createStrategy, /notification_channel_required/)
  assert.match(createStrategy, /manifestDirectionMode\(\)/)
  assert.match(createStrategy, /name="long_only"/)
  assert.match(createStrategy, /name="short_only"/)
  assert.match(createStrategy, /name="one_way"/)
  assert.match(createStrategy, /name="both"/)
  assert.match(createStrategy, /form\.disclaimer/)
  assert.match(createStrategy, /aiDecisionFilter/)
  assert.match(createStrategy, /name="neutral"/)
  assert.match(createStrategy, /directionMode: this\.requiresDirectionMode \? this\.effectiveDirectionMode/)
  assert.match(createStrategy, /positionSide: this\.requiresDirectionMode \? directionModePositionSide/)
  assert.doesNotMatch(createStrategy, /v-model="form\.positionSide"/)
  assert.match(createStrategy, /formValid\(\)/)
  assert.match(createStrategy, /if \(!this\.activeNotificationChannels\.length\) return false/)
  assert.match(createStrategy, /:disabled="!formValid"/)
  assert.doesNotMatch(createStrategy, /创建机器人/)
})

test('market, chart, and accounts provide a complete mobile path', () => {
  const market = read('src/views/market/index.vue')
  const chart = read('src/views/indicator/Chart.vue')
  const profile = read('src/views/v2/ProfileHub.vue') + read('src/views/profile/Account.vue') + read('src/views/profile/Language.vue')
  const credentials = read('src/views/profile/Credentials.vue')

  assert.match(market, /emptyStateTitle/)
  assert.match(market, /view_my_strategies/)
  assert.match(market, /role="tab"/)
  assert.match(read('src/components/MarketChart.vue'), /from 'klinecharts'/)
  assert.match(read('src/components/ChartTradePanel.vue'), /quickTradeApi\.placeOrder/)
  assert.match(read('src/components/ChartTradePanel.vue'), /credentialsApi\.list/)
  assert.match(profile, /router\.push\('\/profile\/credentials'\)/)
  assert.match(profile, /ExchangeLogo/)
  assert.match(credentials, /credentialHealthLabel/)
})

test('AI composer stays at the bottom and uses a text send action', () => {
  const aiHub = read('src/views/ai-hub/index.vue') + read('src/locales/ai-chat.js')
  const api = read('src/api/index.js')
  const styles = read('src/styles/index.css')

  assert.match(aiHub, /\{\{ text\.send \}\}/)
  assert.doesNotMatch(aiHub, /class="avatar"|ai-avatar-mark/)
  assert.match(aiHub, /\.message-row\.assistant \.bubble-wrap\s*\{\s*width: 100%/)
  assert.match(styles, /--page-gutter: 10px/)
  assert.match(aiHub, /class="report-feature-card"[\s\S]*?<div class="starter-grid">/)
  assert.match(aiHub, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
  assert.doesNotMatch(aiHub, /bottom-suggestions/)
  assert.match(aiHub, /\.send-action[\s\S]*min-width: 72px/)
  assert.match(aiHub, /sendMessageReliable\(payload, pendingMsg\)/)
  assert.match(aiHub, /await this\.sendMessageStream\(payload, pendingMsg\)[\s\S]*aiChatApi\.sendMessage\(\{/)
  assert.match(api, /sendMessage: \(payload\) => http\.post\('\/api\/ai\/chat\/message', payload, \{ timeout: 600000 \}\)/)
  assert.match(api, /streamMessage:[\s\S]*\/api\/ai\/chat\/message\/stream/)
  assert.match(api, /if \(await handlePart\(part\) === 'done'\)[\s\S]*await reader\.cancel\(\)/)
  assert.match(aiHub, /if \(!streamResult\?\.completed\)[\s\S]*throw new Error\(this\.text\.streamIncomplete\)/)
  assert.match(aiHub, /error\.streamAccepted = streamAccepted[\s\S]*if \(error\?\.streamAccepted \|\| error\?\.streamHasContent\)[\s\S]*return/)
  assert.match(aiHub, /event === 'replace'[\s\S]*content: text/)
  assert.match(aiHub, /event === 'warning'[\s\S]*streamWarning/)
})

test('mobile overlays and AI message actions stay above the persistent tab bar', () => {
  const aiHub = read('src/views/ai-hub/index.vue') + read('src/locales/ai-chat.js')
  const market = read('src/views/market/index.vue')

  assert.match(market, /showStrategyFilters[\s\S]*class="strategy-filter-popup"[\s\S]*teleport="body"/)
  assert.match(market, /\.strategy-filter-popup\s*\{[\s\S]*overflow-y: auto;/)
  assert.match(aiHub, /\.chat-panel\s*\{\s*flex: 1 1 0;\s*min-height: 0;/)
  assert.match(aiHub, /\.message-list\s*\{\s*height: 100%;\s*min-height: 0;/)
  assert.doesNotMatch(aiHub, /height: calc\(100vh - 220px/)
})

test('AI Copilot keeps mobile research focused on chat, reports, and conversation memory', () => {
  const aiHub = read('src/views/ai-hub/index.vue') + read('src/locales/ai-chat.js')
  const api = read('src/api/index.js')
  const router = read('src/router/index.js')

  assert.doesNotMatch(aiHub, /showQuickTools|quick-task-grid|tools-inline-btn|text\.quickTools/)
  assert.doesNotMatch(aiHub, /class="research-preset-row"|selectResearchPreset\(preset\)/)
  assert.match(aiHub, /class="report-feature-card"[\s\S]*@click="confirmProfessionalAnalysis"/)
  assert.match(aiHub, /class="memory-action"[\s\S]*@click="openMemoryPanel"/)
  assert.match(aiHub, /referenced_report_id: referencedReportId \|\| null/)
  assert.match(aiHub, /context_usage \|\| data\?\.contextUsage/)
  assert.match(aiHub, /reportRiskReward\(msg\.report\)/)
  assert.match(aiHub, /reportHasRrWarning\(msg\.report\)/)
  assert.match(aiHub, /plan\.candidate_setup \|\| plan/)
  assert.doesNotMatch(aiHub, /copilot_recent_messages|user_memories/)
  assert.match(api, /getSessionMemory: \(sessionId\) => http\.get\(`\/api\/ai\/chat\/sessions\/\$\{sessionId\}\/memory`\)/)
  assert.match(api, /clearSessionMemory: \(sessionId\) => http\.delete\(`\/api\/ai\/chat\/sessions\/\$\{sessionId\}\/memory`\)/)
  assert.match(api, /getUserMemory:[\s\S]*\/api\/ai\/memory/)
  assert.doesNotMatch(aiHub, /class="research-tool-strip"|openResearchTool\(/)
  assert.doesNotMatch(aiHub, /shareProfessionalReport\(msg\)|exportProfessionalReport\(msg\)/)
  assert.doesNotMatch(api, /\/api\/ai\/prompt-library|\/api\/portfolio\/monitors|\/api\/ai\/chat\/report\/pdf|\/api\/ai\/chat\/report\/share/)
  assert.doesNotMatch(router, /path: '\/report\/share\/:token'/)
})

test('signal chart supports mobile timeframe navigation and direct order context', () => {
  const chart = read('src/views/indicator/Chart.vue')

  const renderer = read('src/components/MarketChart.vue')
  const panel = read('src/components/ChartTradePanel.vue')
  assert.match(chart, /form.timeframe=time;loadChart\(\)/)
  assert.match(chart, /'1m','5m','15m','30m','1H','4H','1D','1W'/)
  assert.match(renderer, /createIndicator\('VOL'/)
  assert.match(renderer, /calcParams:\[20,60\]/)
  assert.match(renderer, /createPlotRenderer/)
  assert.match(panel, /OPEN_ORDER_STATUSES.has/)
  assert.match(chart, /@context-change="onTradeContextChange"/)
  assert.match(chart, /limit:\s*360/)
  assert.doesNotMatch(chart, /strategyApi|orderApi|backtestApi/)
})
